### ISSUE TITLE
Release X.Y.Z - $MONTH $YEAR

### ISSUE THREAD

**Issue by Jock0707** [bazelbuild/bazel#17119]
# Status of Bazel X.Y.Z

-   Target baseline: [date]
-   Expected release date: [date]
-   [List of release blockers](link-to-milestone)

To report a release-blocking bug, please add a comment with the text `@bazel-io flag` to the issue. A release manager will triage it and add it to the milestone.

To cherry-pick a mainline commit into X.Y.Z, simply send a PR against the `release-X.Y.Z` branch.

**Task list:**

-   [ ] Pick release baseline: [link to base commit]
-   [ ] Create release candidate: X.Y.Zrc1
-   [ ] Check downstream projects
-   [ ] Create [draft release announcement](https://docs.google.com/document/d/1pu2ARPweOCTxPsRR8snoDtkC9R51XWRyBXeiC6Ql5so/edit) 
-   [ ] Send the release announcement PR for review: [link to bazel-blog PR] 
-   [ ] Push the release and notify package maintainers: [link to comment notifying package maintainers]
-   [ ] Update the documentation
-   [ ] Push the blog post: [link to blog post] 
-   [ ] Update the [release page](https://github.com/bazelbuild/bazel/releases/)
