### ISSUE TITLE
Release 6.1.0 - March 2023

### ISSUE THREAD

**Issue by kshyanashree** [bazelbuild/bazel#17212]
# Status of Bazel 6.1.0

-   Expected release date: 2023-03-06
-   [List of release blockers](https://github.com/bazelbuild/bazel/milestone/46)

To report a release-blocking bug, please add a comment with the text `@bazel-io flag` to the issue. A release manager will triage it and add it to the milestone.

To cherry-pick a mainline commit into 6.1, simply send a PR against the `release-6.1.0` branch.

**Task list:**

-   [x] Create [draft release announcement](https://docs.google.com/document/d/1pu2ARPweOCTxPsRR8snoDtkC9R51XWRyBXeiC6Ql5so/edit) 
-   [x] Send the release announcement for review
-   [x] Push the release and notify package maintainers
-   ~Update the documentation~
-   [x] Update the [release page](https://github.com/bazelbuild/bazel/releases/)

**Comment by brentleyjones** [comment]
Looks like there are 11 changes that have already been flagged for 6.1.0, but they haven't been triaged yet: https://github.com/bazelbuild/bazel/issues?q=label%3A%22potential+release+blocker%22+is%3Aclosed

**Comment by BoleynSu** [comment]
[bazel 6.0 does not Remote Test Without the Bytes](https://github.com/bazelbuild/bazel/issues/17534) could this be addressed in the next release?

**Comment by kshyanashree** [comment]
Bazel 6.1.0rc1 is now available for those that want to try it out.

You can download it from:
https://releases.bazel.build/6.1.0/rc1/index.html

Please report regressions to https://github.com/bazelbuild/bazel/issues as soon as possible.

For any cherry-pick requests, please send PRs to the [release-6.1.0](https://github.com/bazelbuild/bazel/tree/release-6.1.0) branch.

**Comment by joeljeske** [comment]
Hello @kshyanashree is there any chance of uploading the releases to Github as well? I think its a common flow with Bazelisk to use Github for Bazel downloads. 🙏

**Comment by meteorcloudy** [comment]
Hi @joeljeske, Bazelisk can also fetch release candidates from the GCS bucket where the Bazel binaries are uploaded to, just set `USE_BAZEL_VERSION=6.1.0rc1`.
https://github.com/bazelbuild/bazelisk#how-does-bazelisk-know-which-bazel-version-to-run

**Comment by joeljeske** [comment]
Makes sense, but due to this issue I cannot reference by binaries in the GCS bucket through my proxy. 

https://github.com/bazelbuild/bazelisk/issues/284

When are binaries expected to be only in the bucket or also on GitHub?

**Comment by meteorcloudy** [comment]
@joeljeske 
All release binaries are published to the GCS bucket, for examples

- official release: https://releases.bazel.build/6.0.0/release/index.html
- release candidate: https://releases.bazel.build/6.1.0/rc1/index.html
- rolling release: https://releases.bazel.build/7.0.0/rolling/7.0.0-pre.20230215.2/index.html

**Comment by kshyanashree** [comment]
Bazel 6.1.0rc2 is now available for those that want to try it out.

You can download it from:
https://releases.bazel.build/6.1.0/rc2/index.html

Please report regressions to https://github.com/bazelbuild/bazel/issues as soon as possible.

**Comment by kshyanashree** [comment]
Bazel 6.1.0rc3 is now available for those that want to try it out.

You can download it from:
https://releases.bazel.build/6.1.0/rc3/index.html

Please report regressions to https://github.com/bazelbuild/bazel/issues as soon as possible.

**Comment by kshyanashree** [comment]
6.1.0 is now out!

@petemounce Could you please update Chocolatey? Thanks!

@excitoon [@vbatts](https://github.com/vbatts) Could you please update Scoop & Fedora package with 6.1.0? Thanks!

**Comment by kshyanashree** [comment]
The docker container with the latest Bazel version is  published to gcr.io/bazel-public/bazel.

**Comment by keertk** [comment]
FYI: We're planning to do a patch release (6.1.1) in the coming days to fix a regression (https://github.com/bazelbuild/bazel/issues/17686). We'll update here when it's out.

**Comment by kshyanashree** [comment]
Bazel 6.1.1rc1 is now available for those that want to try it out.

You can download it from:
https://releases.bazel.build/6.1.1/rc1/index.html

Please report regressions to https://github.com/bazelbuild/bazel/issues as soon as possible.

**Comment by kshyanashree** [comment]
Bazel 6.1.1rc2 is now available for those that want to try it out.

You can download it from:
https://releases.bazel.build/6.1.1/rc2/index.html

Please report regressions to https://github.com/bazelbuild/bazel/issues as soon as possible.

**Comment by kshyanashree** [comment]
6.1.1 is now out!

@petemounce Could you please update Chocolatey? Thanks!

@excitoon [@vbatts](https://github.com/vbatts) Could you please update Scoop & Fedora package with 6.1.1? Thanks!
