### ISSUE TITLE
incompatible_python_disable_py2

### ISSUE THREAD

**Issue by rickeylev** [bazelbuild/bazel#17293]
This issue tracks enabling `--incompatible_python_disable_py2` (implemented in https://github.com/bazelbuild/bazel/commit/d1bbf4b7698e019c11b7d1c483eb0b4959954060) as part of #15684 

When enabled, the Python rules will reject Python 2 only attribute values. This includes:
  * `python_version=PY2`
  * `srcs_version=PY2` and `srcs_version=PY2ONLY`
  * Setting `py2_runtime`

To fix, you must update your rules (or dependencies) to not set these Python 2 values:
  * For `srcs_version`: remove the attribute.
  * For `py2_runtime`: remove the attribute.
  * For `python_version`: remove the attribute from `py_binary` and `py_test`. For `py_runtime`, 
    the entire target can be deleted, as there is nothing that can use it.

Note that the `PyInfo` and `PyRuntimeInfo` providers do not raise an error. This is simply because providers can't access flags to know whether to enforce behavior; code should still be updated as appropriate:
  * For PyInfo, stop reading/writing `has_py2_only_sources` and `has_py3_only_sources`.
  * For PyRuntimeInfo, set `python_version=PY3`

Most of this can be automated using [buildozer](https://github.com/bazelbuild/buildtools/tree/master/buildozer)

```
remove python_version //...%py_binary
remove python_version //...%py_test
remove srcs_version //...%py_binary
remove srcs_version //...%py_test
remove srcs_version //...%py_library
remove py2_runtime //...%py_runtime_pair
```

It may not be your code with a problem, but a dependency. In this case, you probably just need to update your dependency to a newer version -- most projects no longer require Python 2.
  * For rules_pkg, upgrade to 0.3.0 or greater

**Comment by keertk** [comment]
**Failures:** https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1408

<img width="1159" alt="image" src="https://user-images.githubusercontent.com/110264242/215143977-12f7daa0-42e7-4c78-8ca7-dffb28671558.png">

**To fix:**

- [ ] **Bazel toolchains:** [tbd]
- [ ] **rules_foreign_cc:** [tbd]
- [ ] **rules_jvm_external:** [tbd]
- [ ] **rules_nodejs:** [tbd]

**Comment by rickeylev** [comment]
Thanks. Copying the list so I can edit it myself.

* [ ]  **Bazel toolchains:** [Flag --incompatible_python_disable_py2 will break Bazel toolchains in Bazel 7.0 bazel-toolchains#995](https://github.com/bazelbuild/bazel-toolchains/issues/995)
* [ ]  **rules_foreign_cc:** [Flag --incompatible_python_disable_py2 will break rules_foreign_cc in Bazel 7.0 rules_foreign_cc#1005](https://github.com/bazelbuild/rules_foreign_cc/issues/1005)
  * Sent https://github.com/bazelbuild/rules_foreign_cc/pull/1006
* [ ]  **rules_jvm_external:** [Flag --incompatible_python_disable_py2 will break rules_jvm_external in Bazel 7.0 rules_jvm_external#846](https://github.com/bazelbuild/rules_jvm_external/issues/846)
* [ ]  **rules_nodejs:** [Flag --incompatible_python_disable_py2 will break rules_nodejs in Bazel 7.0 rules_nodejs#3619](https://github.com/bazelbuild/rules_nodejs/issues/3619)

**Comment by rickeylev** [comment]
Hi @keertk 

Can you trigger another incompatible build? I'm about ready to flip this flag, but would like another run to double check things.

**Comment by keertk** [comment]
Sure! Here: https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1415

**Comment by keertk** [comment]
So looks rules_nodejs is still failing:
https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1415#01860f63-baf7-4523-a762-c201d59cb82b
https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1415#01860f63-bafa-4e7a-ae47-540d7218134d
https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1415#01860f63-bb0b-4196-95dc-73a715caf534
https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1415#01860f63-bb0d-41de-82b7-cbb14c1991d9

Everything else looks good!

**Comment by rickeylev** [comment]
Thanks.

From what I can tell, the version of nodejs the pipeline used doesn't contain my fix. The pipeline used e5c7a3d0013d257fec4db5c3a01a2050a9a7c6d1. I have no idea why? I can see my fix merged into nodejs's stable branch. I don't see where the pipeline gets the commit to check out from, though. The nodejs commit with my fix is 4b8bcf2f7c07d2f44a2fa7c6ce1f7431d277f7ed

Any ideas? Is this the fault of the incompatible-flags pipeline (does it need to be started anew?), or some fault in nodejs's configuration that incompatible-flags pipeline reads? (I can't find any indication in their .bazelci config that would indicate such).

**Comment by keertk** [comment]
@rickeylev checking and will keep you posted!

**Comment by rickeylev** [comment]
I was digging around trying to find anything. I found this another invocation:

```
BUILDKITE_COMMAND="curl -sS https://raw.githubusercontent.com/bazelbuild/continuous-integration/master/buildkite/bazelci.py?1675462537 -o bazelci.py
python3.6 bazelci.py runner --task=ubuntu1804 --http_config=https://raw.githubusercontent.com/bazelbuild/rules_nodejs/stable/.bazelci/presubmit.yml --git_repository=https://github.com/bazelbuild/rules_nodejs.git --git_commit=e5c7a3d0013d257fec4db5c3a01a2050a9a7c6d1 --use_but"
```

from https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1419#0186195a-0aa4-4b42-ba61-9a8334058e66

Note the --git_commit is using the commit that is too old. I can't find where that is set, though. There must be something that sets that variable, though.

**Comment by rickeylev** [comment]
I found a bit of code in bazelci.py that seems to indicate that it will use the last green commit of a project. rules_nodejs says its red right now so....maybe that's it.

**Comment by rickeylev** [comment]
Except for the rules_nodejs issue, this flag is ready to flip. (As far as I know, of course)

After talking with Yun, I'm going to submit the flag flip now. It _technically_ will show as breaking rules_nodejs, but rules_nodejs is, due to pre-existing failures, stuck at an older commit that doesn't have the necessary fix (the fix is using rules_pkg version 0.3.0+).
