### ISSUE TITLE
Release 6.1.2 - April 2023

### ISSUE THREAD

**Issue by keertk** [bazelbuild/bazel#18031]
# Status of Bazel 6.1.2

-   Expected release date: 2023-04-18
-   [List of release blockers](https://github.com/bazelbuild/bazel/milestone/51)

To report a release-blocking bug, please add a comment with the text `@bazel-io flag` to the issue. A release manager will triage it and add it to the milestone.

To cherry-pick a mainline commit into 6.1.2, simply send a PR against the `release-6.1.2` branch.

**Task list:**

-   [x] Create [draft release announcement](https://docs.google.com/document/d/1pu2ARPweOCTxPsRR8snoDtkC9R51XWRyBXeiC6Ql5so/edit) 
-   [x] Push the release and notify package maintainers
-   [x] Update the [release page](https://github.com/bazelbuild/bazel/releases/)

**Comment by kshyanashree** [comment]
Bazel 6.1.2rc1 is now available for those that want to try it out.

You can download it from:
https://releases.bazel.build/6.1.2/rc1/index.html

Please report regressions to https://github.com/bazelbuild/bazel/issues as soon as possible.

**Comment by keertk** [comment]
6.1.2 RC2 is now available and can be downloaded from [https://releases.bazel.build/6.1.2/rc2/index.html](https://releases.bazel.build/6.1.2/rc2/index.html)

Please report regressions to https://github.com/bazelbuild/bazel/issues as soon as possible, thanks!

**Comment by petemounce** [comment]
Released. Ping for @meteorcloudy + https://github.com/bazelbuild/continuous-integration/issues/1456?

**Comment by darrenrabbs** [comment]
I recently upgraded to this version, but I am seeing issues using bazel coverage , this was previously working with 5.4.1.
Seeing empty coverage.dat files - any update on https://github.com/bazelbuild/bazel/issues/18833 would be great. Do we have any workarounds for this ?

**Comment by keertk** [comment]
Hi @c-mita could you help with this? ^

**Comment by c-mita** [comment]
"empty coverage.dat files" is too vague to do anything with. What are you actually doing?
