### ISSUE TITLE
Release 5.4.1 - April 2023

### ISSUE THREAD

**Issue by keertk** [bazelbuild/bazel#18032]
# Status of Bazel 5.4.1

-   Expected release date: 2023-04-13
-   [List of release blockers](https://github.com/bazelbuild/bazel/milestone/50)

To report a release-blocking bug, please add a comment with the text `@bazel-io flag` to the issue. A release manager will triage it and add it to the milestone.

To cherry-pick a mainline commit into 5.4.1, simply send a PR against the `release-5.4.1` branch.

**Task list:**

-   [ ] Create [draft release announcement](https://docs.google.com/document/d/1pu2ARPweOCTxPsRR8snoDtkC9R51XWRyBXeiC6Ql5so/edit) 
-   [ ] Push the release and notify package maintainers
-   [ ] Update the [release page](https://github.com/bazelbuild/bazel/releases/)

**Comment by keertk** [comment]
5.4.1 RC2 is now available and can be downloaded from https://releases.bazel.build/5.4.1/rc2/index.html

Please report regressions to https://github.com/bazelbuild/bazel/issues as soon as possible, thanks!

**Comment by keertk** [comment]
5.4.1 is out:
- https://github.com/bazelbuild/bazel/releases/tag/5.4.1
- https://releases.bazel.build/5.4.1/release/index.html

cc @petemounce @excitoon @vbatts for updating the Chocolatey, Scoop, and Fedora packages. Thank you.

**Comment by petemounce** [comment]
Released. Ping for @meteorcloudy + https://github.com/bazelbuild/continuous-integration/issues/1456?
