### ISSUE TITLE
Release 4.2.4 - April 2023

### ISSUE THREAD

**Issue by keertk** [bazelbuild/bazel#18033]
# Status of Bazel 4.2.4

-   Expected release date: 2023-04-20
-   [List of release blockers](https://github.com/bazelbuild/bazel/milestone/52)

To report a release-blocking bug, please add a comment with the text `@bazel-io flag` to the issue. A release manager will triage it and add it to the milestone.

To cherry-pick a mainline commit into 4.2.4, simply send a PR against the `release-4.2.4` branch.

**Task list:**

-   [x] Create [draft release announcement](https://docs.google.com/document/d/1pu2ARPweOCTxPsRR8snoDtkC9R51XWRyBXeiC6Ql5so/edit) 
-   [ ] Push the release and notify package maintainers
-   [ ] Update the [release page](https://github.com/bazelbuild/bazel/releases/)

**Comment by kshyanashree** [comment]
Bazel 4.2.4rc1 is now available for those that want to try it out.

You can download it from:
https://releases.bazel.build/4.2.4/rc1/index.html

Please report regressions to https://github.com/bazelbuild/bazel/issues as soon as possible.

**Comment by keertk** [comment]
4.2.4 is out:
- https://github.com/bazelbuild/bazel/releases/tag/4.2.4
- https://releases.bazel.build/4.2.4/release/index.html

cc @petemounce @excitoon @vbatts for updating the Chocolatey, Scoop, and Fedora packages. Thank you.

**Comment by petemounce** [comment]
Released. Ping for @meteorcloudy + https://github.com/bazelbuild/continuous-integration/issues/1456?
