### ISSUE TITLE
Release 6.3.0 - July 2023

### ISSUE THREAD

**Issue by iancha1992** [bazelbuild/bazel#18368]
# Status of Bazel 6.3.0

-   Expected first release candidate date: 2023-07-13
-   Expected release date: 2023-07-24
-   [List of release blockers](https://github.com/bazelbuild/bazel/milestone/53)

To report a release-blocking bug, please add a comment with the text `@bazel-io flag` to the issue. A release manager will triage it and add it to the milestone.

To cherry-pick a mainline commit into 6.3.0, simply send a PR against the `release-6.3.0` branch.

**Task list:**

-   [x] Create release candidate
-   [x] Check downstream projects
-   [x] Create [draft release announcement](https://docs.google.com/document/d/1pu2ARPweOCTxPsRR8snoDtkC9R51XWRyBXeiC6Ql5so/edit) 
-   [x] Push the release and notify package maintainers
-   [ ] Update the documentation
-   [x] Update the [release page](https://github.com/bazelbuild/bazel/releases/)

**Comment by iancha1992** [comment]
Bazel 6.3.0rc1 is now available for those that want to try it out.

You can download it from:
https://releases.bazel.build/6.3.0/rc1/index.html

Please report regressions to https://github.com/bazelbuild/bazel/issues as soon as possible.

**Comment by jsharpe** [comment]
https://github.com/bazelbuild/bazel/issues/18936 affects this release.

**Comment by Wyverald** [comment]
6.3.0rc1 is already out, and we can't cherry-pick anything other than regression fixes etc at this point. Your changes will need to wait until 6.4.0.

**Comment by brentleyjones** [comment]
(I'm glad to hear that 6.4.0 is confirmed.)

**Comment by werkt** [comment]
> 6.3.0rc1 is already out, and we can't cherry-pick anything other than regression fixes etc at this point. Your changes will need to wait until 6.4.0.

Alright, I'll pay attention to 6.4.0 news when it comes out, Thanks for the heads up.

**Comment by iancha1992** [comment]
Bazel 6.3.0rc2 is now available for those that want to try it out.

You can download it from:
https://releases.bazel.build/6.3.0/rc2/index.html

Please report regressions to https://github.com/bazelbuild/bazel/issues as soon as possible.

**Comment by fmeum** [comment]
@iancha1992 In an offline discussion, @Wyverald expressed concerns about the complexity introduced by the `isolated` parameter of `use_extension`. Since it is not too late to guard it with an experiment flag, but would be after the 6.3.0 release, we should wait for his confirmation.

**Comment by iancha1992** [comment]
6.3.0 is out:

https://github.com/bazelbuild/bazel/releases/tag/6.3.0
https://releases.bazel.build/6.3.0/release/index.html
cc @excitoon @vbatts for updating Scoop and Fedora packages. Thanks.

**Comment by vbatts** [comment]
would someone like to try their hand at building the rpms for fedora?
I will not be able to do this.

**Comment by keertk** [comment]
Ok, thanks for the info! We'll take a look and get back to you.

**Comment by vbatts** [comment]
On 25/07/23 09:34 -0700, keertk wrote:
>Ok, thanks for the info! We'll take a look and get back to you.

I've just looked into this lightly. 
There is a build of bazel v6.3.1 for fedora 37, but fedora 38 fails with
a new error.

**Comment by meteorcloudy** [comment]
@vbatts Thanks for maintaining the fedora build and looking into the issue! Unfortunately, the Bazel team doesn't have capacity to look into this right now since we don't maintain the package for fedora officially. But if you figure out a fix, we'll be very happy to accept a PR!
