### ISSUE TITLE
Release 6.2.1 - June 2023

### ISSUE THREAD

**Issue by iancha1992** [bazelbuild/bazel#18502]
# Status of Bazel 6.2.1

-   Expected first release candidate date: 2023-05-26
-   Expected release date: 2023-06-02
-   [List of release blockers](https://github.com/bazelbuild/bazel/milestone/54)

To report a release-blocking bug, please add a comment with the text `@bazel-io flag` to the issue. A release manager will triage it and add it to the milestone.

To cherry-pick a mainline commit into 6.2.1, simply send a PR against the `release-6.2.1` branch.

**Task list:**

-   [x] Create release candidate
-   [x] Check downstream projects
-   [x] Create [draft release announcement](https://docs.google.com/document/d/1pu2ARPweOCTxPsRR8snoDtkC9R51XWRyBXeiC6Ql5so/edit)
-   [ ] Push the release and notify package maintainers
-   [ ] Update the [release page](https://github.com/bazelbuild/bazel/releases/)

**Comment by Pavank1992** [comment]
Bazel 6.2.1rc1 is now available for those that want to try it out.

You can download it from:
https://releases.bazel.build/6.2.1/rc1/index.html

Please report regressions to https://github.com/bazelbuild/bazel/issues as soon as possible.

**Comment by iancha1992** [comment]
Bazel 6.2.1rc2 is now available for those that want to try it out.

You can download it from:
https://releases.bazel.build/6.2.1/rc2/index.html

Please report regressions to https://github.com/bazelbuild/bazel/issues as soon as possible.

**Comment by iancha1992** [comment]
6.2.1 is out:

https://github.com/bazelbuild/bazel/releases/tag/6.2.1
https://releases.bazel.build/6.2.1/release/index.html
cc @excitoon @vbatts for updating the Scoop and Fedora packages. Thank you.
