### ISSUE TITLE
Release 7.0.0 - December 2023

### ISSUE THREAD

**Issue by Pavank1992** [bazelbuild/bazel#18548]
# Status of Bazel 7.0.0

-   Expected first release candidate date: October 17, 2023
-   Expected final release candidate date: December 6, 2023
-   Expected release date: December 11, 2023
-   [List of release blockers](https://github.com/bazelbuild/bazel/milestone/55)

To report a release-blocking bug, please add a comment with the text `@bazel-io flag` to the issue. A release manager will triage it and add it to the milestone.

To cherry-pick a mainline commit into 7.0.0, simply send a PR against the `release-7.0.0` branch. (This branch will be created in October.)

**Task list:**

-   [x] Pick release baseline: 0a2aac4e3c6f5ef98fc233e2ce83e44930edb188
-   [x] Create release candidate: https://releases.bazel.build/7.0.0/rc1/index.html
-   [x] Check [downstream projects](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3395)
-   [x] Create [draft release announcement](https://docs.google.com/document/d/1clxBctsjpei40wqqjwiU2EltTzsrf_kvZ4dJyZVqghM/edit#heading=h.oanqk3j2ty6c) 
-   [x] Push the release and notify package maintainers
-   [x] Update the documentation
-   [x] Push the blog post
-   [x] Update the [release page](https://github.com/bazelbuild/bazel/releases/)

**Comment by iancha1992** [comment]
Hi everyone,

Bazel 7.0.0rc1 is now available for those that want to try it out.
You can download it from: https://releases.bazel.build/7.0.0/rc1/index.html.

Please test it out and report any issues [here](https://github.com/bazelbuild/bazel/issues) as soon as possible.

A draft of the release notes can be found [here](https://docs.google.com/document/d/1clxBctsjpei40wqqjwiU2EltTzsrf_kvZ4dJyZVqghM/edit?usp=sharing).

**Comment by iancha1992** [comment]
Hi everyone,

Bazel 7.0.0rc2 is now available for those that want to try it out.

You can download it from: https://releases.bazel.build/7.0.0/rc2/index.html.
If you're using Bazelisk, you can point to the latest RC by setting USE_BAZEL_VERSION=last_rc.

Please report regressions [here](https://github.com/bazelbuild/bazel/issues) as soon as possible.
Draft release notes can be found [here](https://docs.google.com/document/d/1clxBctsjpei40wqqjwiU2EltTzsrf_kvZ4dJyZVqghM/edit?usp=sharing).

**Comment by sfc-gh-jmerino** [comment]
I've been testing Bazel 7 but just now realized that I was using an "ancient" pre-release (7.0.0-pre.20231011.2 instead of 7.0.0rc2) because... I was looking for the candidates in the wrong place.

Issues:

* All previous prereleases show up under https://github.com/bazelbuild/bazel/releases , but none of the RCs do.
* The pages linked above don't look professional. There are broken characters everywhere and the pages don't integrate with the Bazel site.
* Downloads feel super-slow compared to downloads from GitHub releases.
* The top-level directory inside the release tarballs is "broken". Typically, unpacking `bazel-7.0.0rc2.tar.gz` should result in a `bazel-7.0.0rc2` directory... but what I get is a `bazel` directory. This does not follow standard practice in any open source distribution, and also does not match what Bazel has been doing in all previous releases.

What's going on here? This looks very sketchy and does not inspire confidence.

**Comment by jmmv** [comment]
I've been testing Bazel 7 but just now realized that I was using an "ancient" pre-release (7.0.0-pre.20231011.2 instead of 7.0.0rc2) because... I was looking for the candidates in the wrong place.

Issues:

* All previous prereleases show up under https://github.com/bazelbuild/bazel/releases , but none of the RCs do.
* The pages linked above don't look professional. There are broken characters everywhere and the pages don't integrate with the Bazel site.
* Downloads feel super-slow compared to downloads from GitHub releases.
* The top-level directory inside the release tarballs is "broken". Typically, unpacking bazel-7.0.0rc2.tar.gz should result in a bazel-7.0.0rc2 directory... but what I get is a bazel directory. This does not follow standard practice in any open source distribution, and also does not match what Bazel has been doing in all previous releases.

What's going on here? This looks very sketchy and does not inspire confidence.

**Comment by Wyverald** [comment]
FWIW, the RC setup has always been like this; nothing has changed (at least in the past 3 years or so). That's not to say the situation is great; we could certainly get rid of the unstyled HTML pages.

Regarding the "ancient" pre-releases, those are [rolling releases](https://bazel.build/release#rolling-releases) that are cut from HEAD roughly every 2 weeks. Those are very different from RCs.

**Comment by keertk** [comment]
@AustinSchuh we have quite a few [release blockers](https://github.com/bazelbuild/bazel/milestone/55) that are currently being worked on for Bazel 7.
We're hoping to have the final release in the next couple of weeks but will post here if anything changes.

**Comment by keertk** [comment]
Bazel 7.0.0rc3 is now available - https://releases.bazel.build/7.0.0/rc3/index.html.

Please test it out and report any issues here as soon as possible. Draft release notes can be found [here](https://docs.google.com/document/d/1clxBctsjpei40wqqjwiU2EltTzsrf_kvZ4dJyZVqghM/edit?usp=sharing). Thanks!

**Comment by iancha1992** [comment]
Bazel 7.0.0rc4 is now available - https://releases.bazel.build/7.0.0/rc4/index.html.

Please test it out and report any issues here as soon as possible. Draft release notes can be found [here](https://docs.google.com/document/d/1clxBctsjpei40wqqjwiU2EltTzsrf_kvZ4dJyZVqghM/edit?usp=sharing). Thanks.

**Comment by iancha1992** [comment]
Bazel 7.0.0rc4 is now available - https://releases.bazel.build/7.0.0/rc4/index.html.

Please test it out and report any issues here as soon as possible. Draft release notes can be found [here](https://docs.google.com/document/d/1clxBctsjpei40wqqjwiU2EltTzsrf_kvZ4dJyZVqghM/edit?usp=sharing). Thanks!

**Comment by rsalvador** [comment]
Bazel 7.0.0rc3 was building without problems our big monorepo, but 7.0.0rc4 fails with errors, e.g.:
```
WARNING: /Users/rsalvador/.../BUILD.bazel:3:17: output 'ui-services-connection-models-api/modelbuilder_generated' of //ui-services-connection-models-api:ui_services_connection_model is a directory; dependency checking of directories is unsound
ERROR: /Users/rsalvador/.../BUILD.bazel:3:17: modelbuilder generating srcjar modelbuilder_generated.srcjar failed: Exec failed due to IOException: /Users/rsalvador/.cache/bazel/b6de016d545fc335c6fe85486d422c54/execroot/core/bazel-out/darwin_x86_64-fastbuild/bin/ui-services-connection-models-api/modelbuilder_generated (No such file or directory)
```

and

```
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ActionLookupData6{actionLookupKey=ConfiguredTargetKey{label=//tools/build/bazel/rules/lwc/js:bundle, config=BuildConfigurationKey[6aa701ced8cd3692bfda0c63eeb4de6bb53c8649464bf1688db8c6f5976ed915]}, actionIndex=6}' (requested by nodes 'ArtifactNestedSetKey[6]@774500339', 'ArtifactNestedSetKey[5]@1662963755')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:550)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:414)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.UnsupportedOperationException: Cannot get node id for RegularFileArtifactValue{digest=e58e4f6d4f57ab1e4a503a523d1c4e34ed03eee292a0237a898ac158c1b7bc69, size=1080, proxy=ctime of 1700240624111 and mtime of 499162500000 and nodeId of 2582129255}
	at com.google.devtools.build.lib.remote.RemoteActionFileSystem$2.getNodeId(RemoteActionFileSystem.java:634)
	at com.google.devtools.build.lib.vfs.DigestUtils$CacheKey.<init>(DigestUtils.java:67)
	at com.google.devtools.build.lib.vfs.DigestUtils.manuallyComputeDigest(DigestUtils.java:193)
	at com.google.devtools.build.lib.vfs.DigestUtils.getDigestWithManualFallback(DigestUtils.java:160)
	at com.google.devtools.build.lib.exec.SpawnLogContext.computeDigest(SpawnLogContext.java:348)
	at com.google.devtools.build.lib.exec.SpawnLogContext.listDirectoryContents(SpawnLogContext.java:296)
	at com.google.devtools.build.lib.exec.SpawnLogContext.logSpawn(SpawnLogContext.java:130)
	at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:192)
	at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:119)
	at com.google.devtools.build.lib.exec.SpawnStrategyResolver.exec(SpawnStrategyResolver.java:45)
	at com.google.devtools.build.lib.analysis.actions.SpawnAction.execute(SpawnAction.java:261)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.executeAction(SkyframeActionExecutor.java:1148)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.run(SkyframeActionExecutor.java:1065)
	at com.google.devtools.build.lib.skyframe.ActionExecutionState.runStateMachine(ActionExecutionState.java:165)
	at com.google.devtools.build.lib.skyframe.ActionExecutionState.getResultOrDependOnFuture(ActionExecutionState.java:94)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:562)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:859)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.computeInternal(ActionExecutionFunction.java:333)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:171)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:461)
```

the first error we can probably fix in our generator, but the internal error may point to some regression?

**Comment by keertk** [comment]
@rsalvador would you mind opening a separate issue for this with more details please?

**Comment by rsalvador** [comment]
@keertk here is the issue https://github.com/bazelbuild/bazel/issues/20246
is there a way of finding out the bazel commits between 7.0.0rc3 and 7.0.0rc4?

**Comment by keertk** [comment]
Thanks! I think you can use [bazelisk bisect](https://github.com/bazelbuild/bazelisk#--bisect) to identify the culprit commit between rc3 and rc4.

**Comment by keertk** [comment]
Update: the final rc (and final release) date has been pushed back by a few days since we're working on a couple of new release blockers.

**Comment by keertk** [comment]
Tentative dates: final release candidate on 11/27 and final release on 11/29.
We'll update here if anything changes!

**Comment by saraadams** [comment]
I looked into the JSON trace profiles (aka Bazel profile) generated. There are multiple changes, which may change code that processes the profile for further analysis (such as we do with https://github.com/EngFlow/bazel_invocation_analyzer). I have not done a full investigation yet, but already discovered the following:

* GC events are now in a thread called `Notification Thread`, whereas previously they were listed in a thread called `Garbage Collector`
    https://github.com/bazelbuild/bazel/commit/a03674e6297ed5f6f740889cba8780d7c4ffe05c introduced the rename from `Service Thread` to `Garbage Collector` - should the code be updated to rename `Notification Thread` to `Garbage Collector` or is the new name intentional?
    If the rename is intentional, are other events reported in this thread, too? Should the rename code be removed, as it may now be dead coce?
    If it is not intentional, an easy fix would be to update `getReadableName` referenced in the patch above.
    (Also see https://github.com/EngFlow/bazel_invocation_analyzer/issues/110)

* Counter events (e.g. for action count, CPU usage, memory usage) no longer have a `tid`. Previously, they had the `tid` of the `Main Thread`, now they are "orphaned".
    https://github.com/bazelbuild/bazel/commit/7e92ed378b9f2829edb50ff89eab829657e5cc48 refactored the code around writing counter series. As part of this refactoring, writhing the `tid` was dropped.
    If I read the [Chrome Trace Event Format Specification](https://docs.google.com/document/d/1CvAClvFfyA5R-PhYUmn5OOQtYMH4h6I0nSsKchNAySU/preview#heading=h.uxpopqvbjezh) correctly, all events should have a thread ID. So perhaps these events should be "re-attached" to the `Main Thread` by including its `tid` again.
    (Also see https://github.com/EngFlow/bazel_invocation_analyzer/issues/113)

**Comment by saraadams** [comment]
@meisterT as the author of https://github.com/bazelbuild/bazel/commit/7e92ed378b9f2829edb50ff89eab829657e5cc48

**Comment by meisterT** [comment]
Thanks for checking, Sara! Both things are likely not intentional. I'm OOO the next few days, but feel free to send PRs to fix them in the meantime.

**Comment by saraadams** [comment]
> Thanks for checking, Sara! Both things are likely not intentional. I'm OOO the next few days, but feel free to send PRs to fix them in the meantime.

I sent two PRs. With a locally built Bazel, I could no longer observe the two described issues. Also verified that 6.4.0 is not affected.

**Comment by AustinSchuh** [comment]
I'm getting worse behavior on https://github.com/bazelbuild/bazel/issues/12712#issuecomment-1801477114 than bazel 6.  It feels like something broke `BAZEL_DO_NOT_DETECT_CPP_TOOLCHAIN`  I used to be able to work around it, now I'm struggling to find a way.

**Comment by keertk** [comment]
Update: due to [open release blockers](https://github.com/bazelbuild/bazel/milestone/55) and ongoing network issues, we've moved the final RC to later this week and final release to next week.

**Comment by iancha1992** [comment]
Bazel 7.0.0rc5 is now available - https://releases.bazel.build/7.0.0/rc5/index.html.

Please test it out and report any issues here as soon as possible. Draft release notes can be found [here](https://docs.google.com/document/d/1clxBctsjpei40wqqjwiU2EltTzsrf_kvZ4dJyZVqghM/edit?usp=sharing). Thanks!

**Comment by rsalvador** [comment]
Verified https://github.com/bazelbuild/bazel/issues/20246 is fixed in 7.0.0rc5

**Comment by iancha1992** [comment]
Bazel 7.0.0rc6 is now available - https://releases.bazel.build/7.0.0/rc6/index.html.

Please test it out and report any issues here as soon as possible. Draft release notes can be found [here](https://docs.google.com/document/d/1clxBctsjpei40wqqjwiU2EltTzsrf_kvZ4dJyZVqghM/edit?usp=sharing). Thanks!

**Comment by saraadams** [comment]
No regression from  7.0.0rc5 to 7.0.0rc6 re https://github.com/bazelbuild/bazel/issues/18548#issuecomment-1823361627

**Comment by konste** [comment]
Bazel 7.0.0 regressed errors reporting when `--keep_going` is specified: https://github.com/bazelbuild/bazel/issues/20443

**Comment by iancha1992** [comment]
7.0.0 is out:

https://github.com/bazelbuild/bazel/releases/tag/7.0.0
https://releases.bazel.build/7.0.0/release/index.html
cc @excitoon @vbatts for updating Scoop and Fedora packages. Thanks.

**Comment by chiragramani** [comment]
Looks like `--jobs` is ignored in Bazel 7, more in this issue: https://github.com/bazelbuild/bazel/issues/20521
