### ISSUE TITLE
Release X.Y.Z - $MONTH $YEAR

### ISSUE THREAD

**Issue by jacobjohnsonutra** [bazelbuild/bazel#18569]
# Status of Bazel X.Y.Z

-   Expected first release candidate date: [date]
-   Expected release date: [date]
-   [List of release blockers](link-to-milestone)

To report a release-blocking bug, please add a comment with the text `@bazel-io flag` to the issue. A release manager will triage it and add it to the milestone.

To cherry-pick a mainline commit into X.Y.Z, simply send a PR against the `release-X.Y.Z` branch.

**Task list:**

-   [x] Pick release baseline: [link to base commit]
-   [x] Create release candidate: X.Y.Zrc1
-   [x] Check downstream projects
-   [x] Create [draft release announcement](https://docs.google.com/document/d/1pu2ARPweOCTxPsRR8snoDtkC9R51XWRyBXeiC6Ql5so/edit) 
-   [x] Send the release announcement PR for review: [link to bazel-blog PR] 
-   [x] Push the release and notify package maintainers: [link to comment notifying package maintainers]
-   [x] Update the documentation
-   [x] Push the blog post: [link to blog post] 
-   [x] Update the [release page](https://github.com/bazelbuild/bazel/releases/)

**Comment by jacobjohnsonutra** [comment]
Begin
