### ISSUE TITLE
Release 6.4.0 - October 2023

### ISSUE THREAD

**Issue by iancha1992** [bazelbuild/bazel#19035]
# Status of Bazel 6.4.0

-   Expected first release candidate date: 2023-10-10
-   Expected release date: 2023-10-19
-   [List of release blockers](https://github.com/bazelbuild/bazel/milestone/57)

To report a release-blocking bug, please add a comment with the text `@bazel-io flag` to the issue. A release manager will triage it and add it to the milestone.

To cherry-pick a mainline commit into 6.4.0, simply send a PR against the `release-6.4.0` branch.

**Task list:**

-   [x] Create release candidate
-   [x] Check downstream projects
-   [x] Create [draft release announcement](https://docs.google.com/document/d/1pu2ARPweOCTxPsRR8snoDtkC9R51XWRyBXeiC6Ql5so/edit) 
-   [x] Push the release and notify package maintainers
-   [x] Update the documentation
-   [x] Update the [release page](https://github.com/bazelbuild/bazel/releases/)

**Comment by werkt** [comment]
Requesting 6.4.0 incorporation of remote fixes with https://github.com/bazelbuild/bazel/pull/18959

**Comment by iancha1992** [comment]
The expected first release candidate date has moved to 9/19/2023. There are 2 release blockers. They are currently WIP to be merged to master.

**Comment by iancha1992** [comment]
Bazel 6.4.0rc1 is now available for those that want to try it out.

You can download it from:
https://releases.bazel.build/6.4.0/rc1/index.html

Please report regressions to https://github.com/bazelbuild/bazel/issues as soon as possible.

**Comment by iancha1992** [comment]
@sluongng are you referring to the Acknowledgements section?

**Comment by Wyverald** [comment]
> https://releases.bazel.build/6.4.0/rc1/index.html The font in here looks weird

It's always been like this. We can look at improving those pages.

**Comment by jsharpe** [comment]
https://github.com/bazelbuild/bazel/issues/19621 - would be great if this could be addressed before 6.4.0 goes live.

**Comment by iancha1992** [comment]
Hi Team,
The release for 6.4.0 RC2 has been postponed to next week (10/5) because we still have some release blockers.
Thank you!

**Comment by linzhp** [comment]
@comius Can we include the flag `--incompatible_enable_proto_toolchain_resolution` in this release?

**Comment by iancha1992** [comment]
Hi everyone,
The release for 6.4.0 RC2 has been postponed to next Tuesday, 10/10/2023 because we still have some release blockers.
Thank you!

**Comment by iancha1992** [comment]
Bazel 6.4.0rc2 is now available for those that want to try it out.

You can download it from:
https://releases.bazel.build/6.4.0/rc2/index.html

Please report regressions to https://github.com/bazelbuild/bazel/issues as soon as possible.

**Comment by iancha1992** [comment]
Bazel 6.4.0rc2 is now available for those that want to try it out.

You can download it from:
https://releases.bazel.build/6.4.0/rc2/index.html

Please report regressions to https://github.com/bazelbuild/bazel/issues as soon as possible.

**Comment by iancha1992** [comment]
6.4.0 is out:

https://github.com/bazelbuild/bazel/releases/tag/6.4.0
https://releases.bazel.build/6.4.0/release/index.html
cc @excitoon @vbatts for updating Scoop and Fedora packages. Thanks.
