### ISSUE TITLE
Release 6.3.1 - July 2023

### ISSUE THREAD

**Issue by keertk** [bazelbuild/bazel#19045]
# Status of Bazel 6.3.1

-   Expected first release candidate date: 2023-07-27
-   Expected release date:  2023-07-31
-   [List of release blockers](https://github.com/bazelbuild/bazel/milestone/58)

To report a release-blocking bug, please add a comment with the text `@bazel-io flag` to the issue. A release manager will triage it and add it to the milestone.

To cherry-pick a mainline commit into 6.3.1, simply send a PR against the `release-6.3.1` branch.

**Task list:**

-   [x] Create release candidate
-   [x] Check downstream projects
-   [x] Create [draft release announcement](https://docs.google.com/document/d/1pu2ARPweOCTxPsRR8snoDtkC9R51XWRyBXeiC6Ql5so/edit) 
-   [x] Push the release and notify package maintainers
-   [x] Update the [release page](https://github.com/bazelbuild/bazel/releases/)

**Comment by iancha1992** [comment]
Just an update. The release candidate 1 for 6.3.1 is having errors with the postsubmit test run. Please see, https://buildkite.com/bazel/bazel-bazel/builds/24242#01898e62-40dc-46e9-b8c1-2ce65c0e1cc7

cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
Bazel 6.3.1rc1 is now available for those that want to try it out.

You can download it from:
https://releases.bazel.build/6.3.1/rc1/index.html

Please report regressions to https://github.com/bazelbuild/bazel/issues as soon as possible.

**Comment by vbatts** [comment]
https://copr.fedorainfracloud.org/coprs/vbatts/bazel/build/6237791/
a number of build failures for Fedora and EPEL

**Comment by iancha1992** [comment]
> https://copr.fedorainfracloud.org/coprs/vbatts/bazel/build/6237791/ a number of build failures for Fedora and EPEL

cc: @bazelbuild/triage
