### ISSUE TITLE
Release 6.3.2 - Aug 2023

### ISSUE THREAD

**Issue by iancha1992** [bazelbuild/bazel#19165]
# Status of Bazel 6.3.2

-   Expected first release candidate date: 2023-08-03
-   Expected release date: 2023-08-07
-   [List of release blockers](https://github.com/bazelbuild/bazel/milestone/59)

To report a release-blocking bug, please add a comment with the text `@bazel-io flag` to the issue. A release manager will triage it and add it to the milestone.

To cherry-pick a mainline commit into 6.3.2, simply send a PR against the `release-6.3.2` branch.

**Task list:**

-   [ ] Create release candidate: 6.3.2
-   [ ] Check downstream projects
-   [ ] Create [draft release announcement](https://docs.google.com/document/d/1pu2ARPweOCTxPsRR8snoDtkC9R51XWRyBXeiC6Ql5so/edit) 
-   [ ] Push the blog post: [link to blog post] 
-   [ ] Update the [release page](https://github.com/bazelbuild/bazel/releases/)

**Comment by keertk** [comment]
RC1 has been pushed to 8/7 due to a problem in the CI. We'll update this issue if there are further changes. Thanks.

**Comment by iancha1992** [comment]
Bazel 6.3.2rc1 is now available for those that want to try it out.

You can download it from:
https://releases.bazel.build/6.3.2/rc1/index.html

Please report regressions to https://github.com/bazelbuild/bazel/issues as soon as possible.

**Comment by iancha1992** [comment]
6.3.2 is out:

https://github.com/bazelbuild/bazel/releases/tag/6.3.2
https://releases.bazel.build/6.3.2/release/index.html
cc @excitoon @vbatts for updating the Scoop and Fedora packages. Thank you.

Edit: @vbatts - we've yet to look into into the instructions you shared to see if we can take this on, unfortunately. We'll keep you posted.
