### ISSUE TITLE
Release 7.1.0 - February 2024

### ISSUE THREAD

**Issue by iancha1992** [bazelbuild/bazel#20471]
# Status of Bazel 7.1.0

-   Expected first release candidate date: 2024-02-21
-   Expected release date: 2024-03-11
-   [List of release blockers](https://github.com/bazelbuild/bazel/milestone/62)

To report a release-blocking bug, please add a comment with the text `@bazel-io flag` to the issue. A release manager will triage it and add it to the milestone.

Note: the `release-7.1.0` branch will be created after Bazel 7 is out.

**Task list:**

-   [x] Create release candidate
-   [x] Check downstream projects
-   [x] Create [draft release announcement](https://docs.google.com/document/d/1clxBctsjpei40wqqjwiU2EltTzsrf_kvZ4dJyZVqghM/edit)
-   [x] Push the release and notify package maintainers
-   [x] Update the documentation
-   [x] Update the [release page](https://github.com/bazelbuild/bazel/releases/)

**Comment by thesayyn** [comment]
> the `release-7.1.0` branch will be created after Bazel 7 is out.

is it time for it yet?

**Comment by iancha1992** [comment]
> > the `release-7.1.0` branch will be created after Bazel 7 is out.
> 
> is it time for it yet?

Hi @thesayyn. The branch is planned to be created on December 18th (Monday).

**Comment by brentleyjones** [comment]
Any reason to wait? Nothing can get added to the `release-7.0.0` branch, and that will be the base, correct?

**Comment by keertk** [comment]
We're hoping to give it a few days before creating the 7.1 branch, in case something comes up that requires a patch release (we released 7.0 just yesterday).

**Comment by brentleyjones** [comment]
Ahh, that makes sense. Thanks.

**Comment by thesayyn** [comment]
Just checking up on this. I still don't see the 7.1 branch...

**Comment by thesayyn** [comment]
Thank you!

**Comment by iancha1992** [comment]
The "release-7.1.0" branch has now been created

**Comment by zhzhzoo-autra** [comment]
Is google going to upgrade to bazel 7 internally? I have found some incompatibilities here or there like https://github.com/abseil/abseil-cpp/issues/1573. (If google is going to upgrade bazel version I could expect these incompatibilities solved in near future or I would have patch them myself.)

**Comment by meteorcloudy** [comment]
@zhzhzoo-autra Internally, Google a monorepo and a slightly different build system called Blaze. Everything always build at HEAD. But Google does have a lot of open source projects using Bazel and depending on abseil-cpp, but they might be slower to migrate the latest version of Bazel release. If you find any incompatibility, please file an issue to the corresponding projects so that the maintainer is aware of the issue.

**Comment by iancha1992** [comment]
Hi,
The expected date for the first release candidate has been pushed to 2/20/2024. If all goes well with the candidate, then we'll push its final release on 2/27/2024. 

Thank you!

**Comment by gregestren** [comment]
@bazel-io fork 7.2.0

**Comment by keertk** [comment]
Bazel 7.1.0rc1 is now available for those that want to try it out.

You can download it from here: https://github.com/bazelbuild/bazel/releases/tag/7.1.0rc1.
If you're using Bazelisk, you can point to this RC by setting `USE_BAZEL_VERSION=7.1.0rc1`.

Please test it out and report any issues [here](https://github.com/bazelbuild/bazel/issues) as soon as possible.
A draft of the release notes can be found [here](https://docs.google.com/document/d/1clxBctsjpei40wqqjwiU2EltTzsrf_kvZ4dJyZVqghM/edit#heading=h.peunwfuyvcb8).

Thanks!

**Comment by brentleyjones** [comment]
@keertk https://github.com/bazelbuild/bazel/releases/tag/7.1.0rc1. points to https://github.com/bazelbuild/bazel/commit/ee57d991ccb56b78e8af0185f266e9a39554b1d4, which is on `master` instead of `release-7.1.0`. I don't think that's correct.

**Comment by sluongng** [comment]
It would be nice to include https://github.com/bazelbuild/bazel/pull/21246 in 7.1.0

It's a minor improvement that should not have any conflict with existing patches.

**Comment by iancha1992** [comment]
Bazel 7.1.0 is now available: https://github.com/bazelbuild/bazel/releases/tag/7.1.0

cc: @excitoon, @vbatt for updating Scoop and Fedora packages. Thanks.
