### ISSUE TITLE
Release 6.5.0 - January 2024

### ISSUE THREAD

**Issue by iancha1992** [bazelbuild/bazel#20470]
# Status of Bazel 6.5.0

-   Expected first release candidate date: 2024-01-12
-   Expected release date: 2024-01-23
-   [List of release blockers](https://github.com/bazelbuild/bazel/milestone/63)

To report a release-blocking bug, please add a comment with the text `@bazel-io flag` to the issue. A release manager will triage it and add it to the milestone.

To cherry-pick a mainline commit into 6.5.0, simply send a PR against the `release-6.5.0` branch.

**Task list:**

-   [x] Create release candidate
-   [x] Check downstream projects
-   [x] Create [draft release announcement](https://docs.google.com/document/d/1pu2ARPweOCTxPsRR8snoDtkC9R51XWRyBXeiC6Ql5so/edit)
-   [x] Push the release and notify package maintainers
-   [x] Update the documentation
-   [x] Update the [release page](https://github.com/bazelbuild/bazel/releases/)

**Comment by Bravonome2022** [comment]
> # สถานะของ Bazel 6.5.0
> * วันที่คาดว่าจะเปิดตัวผู้สมัครครั้งแรก: 2024-01-10
> * วันที่คาดว่าจะวางจำหน่าย: 2024-01-17
> * [รายชื่อตัวบล็อกการปลดปล่อย](https://github.com/bazelbuild/bazel/milestone/63)
> 
> หากต้องการรายงานข้อผิดพลาดในการบล็อกการเผยแพร่ โปรดเพิ่มความคิดเห็นพร้อมข้อความ `@bazel-io flag` ไปยังปัญหา ผู้จัดการรุ่นจะคัดเลือกและเพิ่มลงในเหตุการณ์สำคัญ
> 
> หากต้องการเลือก mainline commit ใน 6.5.0 เพียงส่ง PR เทียบกับ`release-6.5.0` สาขา
> 
> **รายการงาน:**
> 
> * [ ] สร้างผู้สมัครปล่อยตัว
> * [ ] ตรวจสอบโครงการปลายน้ำ
> * [ ]  สร้าง [ประกาศฉบับร่าง](https://docs.google.com/document/d/1pu2ARPweOCTxPsRR8snoDtkC9R51XWRyBXeiC6Ql5so/edit)
> * [ ] ผลักดันการเปิดตัวและแจ้งผู้ดูแลบรรจุภัณฑ์
> * [ ] อัปเดตเอกสาร
> * [ ]  อัปเดต [หน้าเผยแพร่](https://github.com/bazelbuild/bazel/releases/)

**Comment by iancha1992** [comment]
Hi everyone,

Bazel 6.5.0rc1 is now available for those that want to try it out.
You can download it from: https://releases.bazel.build/6.5.0/rc1/index.html or https://github.com/bazelbuild/bazel/releases/tag/6.5.0rc1.

Please test it out and report any issues [here](https://github.com/bazelbuild/bazel/issues) as soon as possible.

A draft of the release notes can be found [here](https://docs.google.com/document/d/1pu2ARPweOCTxPsRR8snoDtkC9R51XWRyBXeiC6Ql5so/edit?usp=sharing).

**Comment by iancha1992** [comment]
Hi Everyone,

Bazel 6.5.0rc2 is now available for those that want to try it out.

You can download it from here:
    - https://releases.bazel.build/6.5.0/rc2/index.html
    - https://github.com/bazelbuild/bazel/releases/tag/6.5.0rc2

If you're using Bazelisk, you can point to the latest RC by setting USE_BAZEL_VERSION=last_rc.

Please test it out and report any issues [here](https://github.com/bazelbuild/bazel/issues) as soon as possible.
A draft of the release notes can be found [here](https://docs.google.com/document/d/1pu2ARPweOCTxPsRR8snoDtkC9R51XWRyBXeiC6Ql5so/edit#heading=h.wpjznn15h0hc).

**Comment by iancha1992** [comment]
Bazel 6.5.0 is now available:
- https://github.com/bazelbuild/bazel/releases/tag/6.5.0
- https://releases.bazel.build/6.5.0/release/index.html
cc: @excitoon, @vbatts for updating Scoop and Fedora packages. Thanks.
