### ISSUE TITLE
Release 7.0.1 - Jan 2024

### ISSUE THREAD

**Issue by iancha1992** [bazelbuild/bazel#20591]
# Status of Bazel 7.0.1

-   Expected first release candidate date: 2024-01-04
-   Expected release date: 2024-01-18
-   [List of release blockers](https://github.com/bazelbuild/bazel/milestone/64)

To report a release-blocking bug, please add a comment with the text `@bazel-io flag` to the issue. A release manager will triage it and add it to the milestone.

To cherry-pick a mainline commit into 7.0.1, simply send a PR against the `release-7.0.1` branch.

**Task list:**

-   [x] Create release candidate
-   [x] Check downstream projects
-   [x] Create [draft release announcement](https://docs.google.com/document/d/1clxBctsjpei40wqqjwiU2EltTzsrf_kvZ4dJyZVqghM/edit#heading=h.1ldj0zgvx6cd) 
-   [ ] Push the release and notify package maintainers
-   [x] Update the [release page](https://github.com/bazelbuild/bazel/releases/)

**Comment by wscott** [comment]
The release dates have the wrong year. ;-)

**Comment by iancha1992** [comment]
Hi everyone,

Bazel 7.0.1rc1 is now available for those that want to try it out.
You can download it from: https://releases.bazel.build/7.0.1/rc1/index.html.

Please test it out and report any issues [here](https://github.com/bazelbuild/bazel/issues) as soon as possible.

A draft of the release notes can be found [here](https://docs.google.com/document/d/1clxBctsjpei40wqqjwiU2EltTzsrf_kvZ4dJyZVqghM/edit?usp=sharing).

**Comment by iancha1992** [comment]
Hi everyone,

Bazel 7.0.1rc2 is now available for those that want to try it out.
You can download it from: https://releases.bazel.build/7.0.1/rc2/index.html or https://github.com/bazelbuild/bazel/releases/tag/7.0.1rc2.

Please test it out and report any issues [here](https://github.com/bazelbuild/bazel/issues) as soon as possible.

A draft of the release notes can be found [here](https://docs.google.com/document/d/1clxBctsjpei40wqqjwiU2EltTzsrf_kvZ4dJyZVqghM/edit?usp=sharing).

**Comment by iancha1992** [comment]
Bazel 7.0.1 is now available:
- https://github.com/bazelbuild/bazel/releases/tag/7.0.1
- https://releases.bazel.build/7.0.1/release/index.html

cc: @excitoon, @vbatts for updating Scoop and Fedora packages. Thanks.

**Comment by sluongng** [comment]
> This release contains contributions from many people at Google, as well as David Ostrovsky, Fabian Meumertzheim, Siddhartha Bagaria, Tianyu Geng.

@iancha1992 I checked the release note and did not find a change authored by Sid(Siddhartha Bagaria).

So either the release note was cut off, or the credit was wrongly given to other contributors.

**Comment by iancha1992** [comment]
Hi @sluongng! Thanks for pointing them out. I've just added three missing notes for 7.0.1, including https://github.com/bazelbuild/bazel/commit/b84528b0c716f4ea5a84c3b9ae15b2defa0a836c. Please let us know if you need anything else. Thanks.
