### ISSUE TITLE
Release 7.0.2 - Jan 2024

### ISSUE THREAD

**Issue by iancha1992** [bazelbuild/bazel#21000]
# Status of Bazel 7.0.2

-   Expected first release candidate date: 2024-01-23
-   Expected release date: 2024-01-25
-   [List of release blockers](https://github.com/bazelbuild/bazel/milestone/66)

To report a release-blocking bug, please add a comment with the text `@bazel-io flag` to the issue. A release manager will triage it and add it to the milestone.

To cherry-pick a mainline commit into 7.0.2, simply send a PR against the `release-7.0.2` branch.

**Task list:**

-   [x] Create release candidate
-   [x] Check downstream projects
-   [x] Create [draft release announcement](https://docs.google.com/document/d/1clxBctsjpei40wqqjwiU2EltTzsrf_kvZ4dJyZVqghM/edit#heading=h.1ldj0zgvx6cd) 
-   [ ] Push the release and notify package maintainers
-   [ ] Update the [release page](https://github.com/bazelbuild/bazel/releases/)

**Comment by iancha1992** [comment]
Hi Everyone,

Bazel 7.0.2rc1 is now available for those that want to try it out.

You can download it from here:
- https://releases.bazel.build/7.0.2/rc1/index.html
- https://github.com/bazelbuild/bazel/releases/tag/7.0.2rc1

If you're using Bazelisk, you can point to the latest RC by setting USE_BAZEL_VERSION=last_rc.

Please test it out and report any issues [here](https://github.com/bazelbuild/bazel/issues) as soon as possible.
A draft of the release notes can be found [here](https://docs.google.com/document/d/1clxBctsjpei40wqqjwiU2EltTzsrf_kvZ4dJyZVqghM/edit#heading=h.9boumn5bis22).

**Comment by iancha1992** [comment]
Bazel 7.0.2 is now available: https://github.com/bazelbuild/bazel/releases/tag/7.0.2

cc: @excitoon, @vbatts for updating Scoop and Fedora packages. Thanks.
