### ISSUE TITLE
Release 7.1.1 - Mar 2024

### ISSUE THREAD

**Issue by iancha1992** [bazelbuild/bazel#21654]
# Status of Bazel 7.1.1

-   Expected first release candidate date: 2024-03-15
-   Expected release date: 2024-03-21
-   [List of release blockers](https://github.com/bazelbuild/bazel/milestone/69)

To report a release-blocking bug, please add a comment with the text `@bazel-io flag` to the issue. A release manager will triage it and add it to the milestone.

To cherry-pick a mainline commit into 7.1.1, simply send a PR against the `release-7.1.1` branch.

**Task list:**

-   [x] Create release candidate
-   [x] Check downstream projects
-   [x] Create [draft release announcement](https://docs.google.com/document/d/1clxBctsjpei40wqqjwiU2EltTzsrf_kvZ4dJyZVqghM/edit#heading=h.1ldj0zgvx6cd)
-   [x] Push the release and notify package maintainers: [See comment](https://github.com/bazelbuild/bazel/issues/21654#issuecomment-2013306182)
-   [x] Update the [release page](https://github.com/bazelbuild/bazel/releases/)

**Comment by iancha1992** [comment]
Bazel 7.1.1rc1 is now available for those that want to try it out.

You can download it from here: https://github.com/bazelbuild/bazel/releases/tag/7.1.1rc1.
If you're using Bazelisk, you can point to this RC by setting USE_BAZEL_VERSION=7.1.1rc1.

Please test it out and report any issues [here](https://github.com/bazelbuild/bazel/issues) as soon as possible.
A draft of the release notes can be found [here](https://docs.google.com/document/d/1clxBctsjpei40wqqjwiU2EltTzsrf_kvZ4dJyZVqghM/edit#heading=h.cxti71gpb9qj).

Thanks!

**Comment by iancha1992** [comment]
Bazel 7.1.1rc2 is now available for those that want to try it out.

You can download it from here: https://github.com/bazelbuild/bazel/releases/tag/7.1.1rc2.
If you're using Bazelisk, you can point to this RC by setting USE_BAZEL_VERSION=7.1.1rc2.

Please test it out and report any issues [here](https://github.com/bazelbuild/bazel/issues) as soon as possible.
A draft of the release notes can be found [here](https://docs.google.com/document/d/1clxBctsjpei40wqqjwiU2EltTzsrf_kvZ4dJyZVqghM/edit#heading=h.cxti71gpb9qj).

Thanks!

**Comment by iancha1992** [comment]
Bazel 7.1.1 is now available: https://github.com/bazelbuild/bazel/releases/tag/7.1.1

cc: @excitoon, @vbatts for updating Scoop and Fedora packages. Thanks.
