### ISSUE TITLE
Release 7.2.0 - June 2024

### ISSUE THREAD

**Issue by iancha1992** [bazelbuild/bazel#21774]
# Status of Bazel 7.2.0

-   Expected first release candidate date: 2024-05-15
-   Expected release date: 2024-06-10
-   [List of release blockers](https://github.com/bazelbuild/bazel/milestone/68)

To report a release-blocking bug, please add a comment with the text `@bazel-io flag` to the issue. A release manager will triage it and add it to the milestone.

Note: the `release-7.2.0` branch will be created on March 25th, 2024.

**Task list:**

-   [x] Create release candidate
-   [x] Check downstream projects
-   [x] Create [draft release announcement](https://docs.google.com/document/d/1clxBctsjpei40wqqjwiU2EltTzsrf_kvZ4dJyZVqghM/edit)
-   [ ] Push the release and notify package maintainers
-   [ ] Update the documentation
-   [ ] Update the [release page](https://github.com/bazelbuild/bazel/releases/)

**Comment by iancha1992** [comment]
Bazel 7.2.0rc1 is now available for those that want to try it out.

You can download it from here: https://github.com/bazelbuild/bazel/releases/tag/7.2.0rc1
If you're using Bazelisk, you can point to this RC by setting USE_BAZEL_VERSION=7.2.0rc1.

Please test it out and report any issues [here](https://github.com/bazelbuild/bazel/issues) as soon as possible.
A draft of the release notes can be found [here](https://docs.google.com/document/d/1clxBctsjpei40wqqjwiU2EltTzsrf_kvZ4dJyZVqghM/edit#heading=h.3xikwl9p56vf).

Thanks!

**Comment by keertk** [comment]
Bazel 7.2.0rc2 is now available - https://github.com/bazelbuild/bazel/releases/tag/7.2.0rc2
If you're using Bazelisk, you can point to this RC by setting `USE_BAZEL_VERSION=7.2.0rc2`.

Please test it out and report any issues [here](https://github.com/bazelbuild/bazel/issues) as soon as possible.
A draft of the release notes can be found [here](https://docs.google.com/document/d/1clxBctsjpei40wqqjwiU2EltTzsrf_kvZ4dJyZVqghM/edit#heading=h.3xikwl9p56vf).

**Comment by keertk** [comment]
Bazel 7.2.0rc3 is now available - https://github.com/bazelbuild/bazel/releases/tag/7.2.0rc3
If you're using Bazelisk, you can point to this RC by setting `USE_BAZEL_VERSION=7.2.0rc3`.

Please test it out and report any issues [here](https://github.com/bazelbuild/bazel/issues) as soon as possible - **we're aiming to release 7.2 on Monday, 6/10**.
A draft of the release notes can be found [here](https://docs.google.com/document/d/1clxBctsjpei40wqqjwiU2EltTzsrf_kvZ4dJyZVqghM/edit#heading=h.3xikwl9p56vf).
