### ISSUE TITLE
Release 7.1.2 - May 2024

### ISSUE THREAD

**Issue by iancha1992** [bazelbuild/bazel#21887]
# Status of Bazel 7.1.2

-   Expected first release candidate date: 2024-05-06
-   Expected release date: 2024-05-08
-   [List of release blockers](https://github.com/bazelbuild/bazel/milestone/70)

To report a release-blocking bug, please add a comment with the text `@bazel-io flag` to the issue. A release manager will triage it and add it to the milestone.

To cherry-pick a mainline commit into 7.1.2, simply send a PR against the `release-7.1.2` branch.

**Task list:**

-   [x] Create release candidate
-   [x] Check downstream projects
-   [x] Create [draft release announcement](https://docs.google.com/document/d/1clxBctsjpei40wqqjwiU2EltTzsrf_kvZ4dJyZVqghM/edit#heading=h.1ldj0zgvx6cd)
-   [ ] Push the release and notify package maintainers: [See comment](https://github.com/bazelbuild/bazel/issues/21654#issuecomment-2013306182)
-   [ ] Update the [release page](https://github.com/bazelbuild/bazel/releases/)

**Comment by keertk** [comment]
Hey @ahumesky is there a particular change you'd like to include in these releases?

**Comment by ahumesky** [comment]
Sorry, I thought I was in a different tab, this made no sense :)

**Comment by iancha1992** [comment]
We are no longer planning for 7.1.2 release. Closing.

**Comment by keertk** [comment]
Bringing this back to address some high-priority issues before 7.2. 
Release dates updated in the comment above.

**Comment by iancha1992** [comment]
Bazel 7.1.2rc1 is now available for those that want to try it out.

You can download it from here: https://github.com/bazelbuild/bazel/releases/tag/7.1.2rc1
If you're using Bazelisk, you can point to this RC by setting USE_BAZEL_VERSION=7.1.2rc1.

Please test it out and report any issues [here](https://github.com/bazelbuild/bazel/issues) as soon as possible - the final release is scheduled for **Wednesday, 5/8**.
A draft of the release notes can be found [here](https://docs.google.com/document/d/1clxBctsjpei40wqqjwiU2EltTzsrf_kvZ4dJyZVqghM/edit#heading=h.hkps29yzjogd).

Thanks!

**Comment by iancha1992** [comment]
Bazel 7.1.2 is now available: https://github.com/bazelbuild/bazel/releases/tag/7.1.2

cc: @excitoon, @vbatts for updating Scoop and Fedora packages. Thanks.
