### ISSUE TITLE
Release 7.3.0 - August 2024

### ISSUE THREAD

**Issue by keertk** [bazelbuild/bazel#22677]
# Status of Bazel 7.3.0

-   Expected first release candidate date: 2024-07-29
-   Expected release date: 2024-08-12
-   [List of release blockers](https://github.com/bazelbuild/bazel/milestone/72)

To report a release-blocking bug, please add a comment with the text `@bazel-io flag` to the issue. A release manager will triage it and add it to the milestone.

To cherry-pick a mainline commit into 7.3.0, simply send a PR against the `release-7.3.0` branch.

**Task list:**

-   [x] Create release candidate
-   [x] Check downstream projects
-   [x] Create [draft release announcement](https://docs.google.com/document/d/1clxBctsjpei40wqqjwiU2EltTzsrf_kvZ4dJyZVqghM/edit)
-   [x] Push the release and notify package maintainers
-   [x] Update the documentation
-   [x] Update the [release page](https://github.com/bazelbuild/bazel/releases/)

**Comment by iancha1992** [comment]
Bazel 7.3.0rc1 is now available for those that want to try it out.

You can download it from here: https://github.com/bazelbuild/bazel/releases/tag/7.3.0rc1
If you're using Bazelisk, you can point to this RC by setting USE_BAZEL_VERSION=7.3.0rc1.

Please test it out and report any issues [here](https://github.com/bazelbuild/bazel/issues) as soon as possible.
A draft of the release notes can be found [here](https://docs.google.com/document/d/1clxBctsjpei40wqqjwiU2EltTzsrf_kvZ4dJyZVqghM/edit#heading=h.vswxwomb18dc).

Thanks!

**Comment by iancha1992** [comment]
Bazel 7.3.0rc2 is now available for those that want to try it out.

You can download it from here: https://github.com/bazelbuild/bazel/releases/tag/7.3.0rc2
If you're using Bazelisk, you can point to this RC by setting USE_BAZEL_VERSION=7.3.0rc2.

Please test it out and report any issues [here](https://github.com/bazelbuild/bazel/issues) as soon as possible.
A draft of the release notes can be found [here](https://docs.google.com/document/d/1clxBctsjpei40wqqjwiU2EltTzsrf_kvZ4dJyZVqghM/edit#heading=h.vswxwomb18dc).

Thanks!

**Comment by iancha1992** [comment]
Bazel 7.3.0 is now available: https://github.com/bazelbuild/bazel/releases/tag/7.3.0

cc: @excitoon, @vbatts for updating Scoop and Fedora packages. Thanks.
