### ISSUE TITLE
Starlark types

### ISSUE THREAD

**Issue by comius** [bazelbuild/bazel#22935]
# Support type annotations and type checking in Starlark

The first goal is: **correctness and readability of Starlark code**

Other goals are:
- improving efficiency of Starlark interpreter and
- Bazel tech-debt reduction

### Milestone 1 (Q4 2024) - MVP - Bootstraping Starlark types
Design doc: [SEP-001 Bootstrapping Starlark types](https://docs.google.com/document/d/1Sid7EAbBd_w_T7D94Li_f_bK3zMTztFbzIMvcpzo1wY/edit?tab=t.0#heading=h.5mcn15i0e1ch)

Starlark specification is incrementally extended under the `starlark-with-types` branch: https://github.com/bazelbuild/starlark/blob/starlark-with-types/spec.md

Goal: Provide a minimally viable type system in Starlark
- [x] https://github.com/bazelbuild/bazel/issues/24407
- [x] [Primitive types](https://github.com/bazelbuild/bazel/issues/25520)
- [ ] [Unions, Collections](https://github.com/bazelbuild/bazel/issues/25948), functions and constructed types
- [ ] Runtime/dynamic type checks
- [ ] Bazel/Starlark built-in types (struct)
- [ ] Launch MVP

### Backlog

- Providers/classes
- Types for Rules & Symbolic macros
- Types for selects
- Types for Java-Starlark interface / Java annotations
- Support types in tooling & IDEs

**Comment by fmeum** [comment]
Prior art available right now: https://github.com/withered-magic/starpls?tab=readme-ov-file#tips-and-tricks

**Comment by withered-magic** [comment]
Hey, just came across this - the starpls type checker is definitely still a work in progress, but I do have plans to eventually make it invokable outside of the LSP (i.e. as a command-line tool, similar to how `pyright` offers a CLI) if we'd like to re-use some of the existing work here!

**Comment by comius** [comment]
Are there refences of Buck2's type system beyond https://github.com/facebook/starlark-rust/blob/main/docs/types.md?

**Comment by jin** [comment]
Related: static typechecking FR, and relevant pointers to earlier discussions https://github.com/bazelbuild/bazel/issues/7468

(IIUC this bug aims to implement runtime typechecking, a different goal)

**Comment by sluongng** [comment]
@comius you could just see how they are used in Buck2's "prelude" (collection of starlark rules Meta opensourced)

https://github.com/search?q=repo%3Afacebook%2Fbuck2+path%3A%2F%5Eprelude%5C%2F%2F++language%3AStarlark+%2Fdef.*-%3E%2F&type=code
