### ISSUE TITLE
Loading language specific rules removed from Bazel

### ISSUE THREAD

**Issue by comius** [bazelbuild/bazel#23043]
### Motivation

Language specific rules (Protos, Java, C++, Android) are being rewritten to Staralark and **moved from Bazel** into **their rules repositories** (protobuf, rules_java, rules_cc, rules_android, apple_support).

Because of the move the rules need to be loaded from their repositories. This requires adding `load` statements to all `bzl` and `BUILD` files that are using those rules.

### Description

The flag `--incompatible_autoload_externally` accepts a list of rules or symbols (previously part of Bazel) that are automatically loaded from external repositories. For configuration see https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/packages/AutoloadSymbols.java.

Prefixing a symbol with '+', loads the symbol from rules_repository, but keeps the native implementation available in rules_repositories (redirects work).  Symbol without a prefix is loaded and the native implementation is not available. Symbol prefixed with a '-' is not loaded and the native implementation is not available (same as if the symbol was deleted from Bazel).

### Incompatible Flag

--incompatible_autoload_externally

### Migration Guide

Bazel <=7:
TODO

Bazel 8:
The flag introduced incompatibilities because the rules are automatically loaded. For this to work we need to depend on the version of the rules_repostiories that implement the rules.

Required versions:
protobuf - TODO
rules_java - TODO
rules_cc - TODO
rules_android - TODO
apple_support - TODO

With bzlmod the right version is selected automatically. Using WORKSPACE files, this needs to be done manually.

Bazel 9:
Load statements for all of the rules need to be added to BUILD and bzl files. To test the behaviour flag is set to an empty value, that is `--incompatible_autoload_externally=`

Cycles:
TODO

### In which Bazel LTS version will this incompatible change be enabled?

Bazel 9

### Additional Context

In Bazel 8, the flag will be set to the list of rules that are removed **==>** rules are loaded automatically
In Bazel 9, the flag will be set to an empty list **==>** rules are not loaded automatically anymore, load statements must be used

### TODO List

With incompatible flag (highly recommend for incompatible changes having large impact):
- [ ] Implement the incompatible change at Bazel HEAD and guard it behind a flag.
- [ ] Backport the incompatible flag to the latest LTS release.
- [ ] Test the incompatible change with [downstream projects](https://github.com/bazelbuild/continuous-integration/blob/master/docs/downstream-testing.md#bazel-downstream-testing) and inform broken projects.
- [ ] Flip the incompatible flag at Bazel HEAD.
- [ ] Delete the incompatible flag and the old behavior at Bazel HEAD.

**Comment by tpasternak** [comment]
Would it mean they would be just loaded, or downloaded from BCR?

**Comment by tpasternak** [comment]
Just a few questions more:
1. Will it be possible to import locally defined symbols?
2. There are some rulesets mentioned above, I guess rules_python is missing

**Comment by limdor** [comment]
I just stumbled across this flag and I think it is good for migration but after reading some documentation I think in the current form is not very user friendly. Let me try to explain why and maybe you can let me know if you considered that.
If I understood correctly the Bazel vision, it means that in the final goal is to have all rules with the `-` prefix. However, this would require for a user to have internal knowledge on Bazel and knowing what rules are provided by Bazel.
Did you consider something more user friendly to treat all rules in the same way? For example `incompatible_autoload_externally=-all` or `incompatible_autoload_externally=+all`?

**Comment by limdor** [comment]
Just one more thing, I just tried with rules_cc doing the following
`--incompatible_autoload_externally="@rules_cc"`
but I cannot because it seems that some symbols are used by java tools
```
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.IllegalStateException: Symbol 'CcInfo' can't be removed, because it's still used by: java_library, java_import, java_runtime, java_binary, java_common, JavaInfo
```
I then have to manually put all this also in the list like this
`--incompatible_autoload_externally="@rules_cc,JavaInfo,java_import,java_library,java_runtime,java_binary,java_common,java_test,java_plugin"`
But even then, it is still not working because it seems that rules_cc itself is not loading all symbols
`ERROR: /home/limdor/.cache/bazel/_bazel_limdor/a313167c2de5a086f3a3e3c99789f007/external/rules_cc+/cc/common/cc_shared_library_hint_info.bzl:17:35: name 'cc_common' is not defined`

Two questions.
- Is there a way to make this transitive? Meaning, I want to disable rules_cc, just disable whatever is needed also.
- And second, is this flag ready to be used by user? Is it only for some rules? It would be good to have a list of the rules that are ready and the ones that are not. From the description I deduced that for rules_cc should be ready but it seems that is not.

**Comment by jadenPete** [comment]
Question: What's the difference between this flag and `--incompatible_stop_exporting_language_modules`?

**Comment by jmillikin** [comment]
Is it expected that `bazel --incompatible_autoload_externally=` still has `cc_binary`, `cc_library`, etc defined by default instead of needing a `@rules_cc` dependency?

**Comment by limdor** [comment]
@comius could you please clarify if the label `migration-ready` is correct? I tried to use it in several projects without success. There seem to be some internal parts of Bazel or basic Bazel rules relying on builtin symbols. From the experimentation I did, it seems to be ready for some rules but not for some others. If you could improve the description of the ticket to say for which ones is ready it would be great. Below my findings.

I tried with `latest_green` the following (`Using unreleased version at commit 5e15723f63e4887a3e0659756e6cae482a56bcd7`):

- With `--incompatible_autoload_externally=-@rules_cc` I get:

```
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.IllegalStateException: Symbol 'CcInfo' can't be removed, because it's still used by: java_library, java_import, java_runtime, java_binary, java_common, JavaInfo
        at com.google.devtools.build.lib.packages.AutoloadSymbols.<init>(AutoloadSymbols.java:219)
        at com.google.devtools.build.lib.skyframe.SkyframeExecutor.preparePackageLoading(SkyframeExecutor.java:1618)
        at com.google.devtools.build.lib.skyframe.SkyframeExecutor.syncPackageLoading(SkyframeExecutor.java:2875)
        at com.google.devtools.build.lib.skyframe.SkyframeExecutor.sync(SkyframeExecutor.java:2830)
        at com.google.devtools.build.lib.skyframe.SequencedSkyframeExecutor.sync(SequencedSkyframeExecutor.java:285)
        at com.google.devtools.build.lib.runtime.CommandEnvironment.syncPackageLoading(CommandEnvironment.java:810)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:593)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:254)
        at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:606)
        at com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$0(GrpcServerImpl.java:676)
        at io.grpc.Context$1.run(Context.java:566)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
```

Similar error to that it is being reported in https://github.com/bazelbuild/bazel/issues/24317

- With `--incompatible_autoload_externally=-@rules_java` I get:

```
ERROR: /home/limdor/.cache/bazel/_bazel_limdor/7847781caf1fd5388b007bf353d8df72/external/rules_java+/java/private/native.bzl:19:12: name 'java_common' is not defined (did you mean 'cc_common'?)
ERROR: Analysis of target '//dynamic_memory/proc_maps:proc_maps' failed; build aborted: Error loading '@@rules_java+//java:extensions.bzl' for module extensions, requested by @@bazel_tools//:MODULE.bazel:20:32: at /home/limdor/.cache/bazel/_bazel_limdor/7847781caf1fd5388b007bf353d8df72/external/rules_java+/java/extensions.bzl:18:5: at /home/limdor/.cache/bazel/_bazel_limdor/7847781caf1fd5388b007bf353d8df72/external/rules_java+/java/repositories.bzl:20:6: at /home/limdor/.cache/bazel/_bazel_limdor/7847781caf1fd5388b007bf353d8df72/external/rules_java+/toolchains/local_java_repository.bzl:17:6: at /home/limdor/.cache/bazel/_bazel_limdor/7847781caf1fd5388b007bf353d8df72/external/rules_java+/java/toolchains/java_runtime.bzl:16:6: at /home/limdor/.cache/bazel/_bazel_limdor/7847781caf1fd5388b007bf353d8df72/external/rules_java++compatibility_proxy+compatibility_proxy/proxy.bzl:2:6: at /home/limdor/.cache/bazel/_bazel_limdor/7847781caf1fd5388b007bf353d8df72/external/rules_java+/java/bazel/rules/bazel_java_binary_wrapper.bzl:26:6: compilation of module 'java/private/native.bzl' failed: at /home/limdor/.cache/bazel/_bazel_limdor/7847781caf1fd5388b007bf353d8df72/external/rules_java+/java/extensions.bzl:18:5: at /home/limdor/.cache/bazel/_bazel_limdor/7847781caf1fd5388b007bf353d8df72/external/rules_java+/java/repositories.bzl:20:6: at /home/limdor/.cache/bazel/_bazel_limdor/7847781caf1fd5388b007bf353d8df72/external/rules_java+/toolchains/local_java_repository.bzl:17:6: at /home/limdor/.cache/bazel/_bazel_limdor/7847781caf1fd5388b007bf353d8df72/external/rules_java+/java/toolchains/java_runtime.bzl:16:6: at /home/limdor/.cache/bazel/_bazel_limdor/7847781caf1fd5388b007bf353d8df72/external/rules_java++compatibility_proxy+compatibility_proxy/proxy.bzl:2:6: at /home/limdor/.cache/bazel/_bazel_limdor/7847781caf1fd5388b007bf353d8df72/external/rules_java+/java/bazel/rules/bazel_java_binary_wrapper.bzl:26:6: compilation of module 'java/private/native.bzl' failed
```

Eventhough I use rules_java 8.11.0 that is higher than 8.5.0 mentioned in the issue. If I try to force 8.5.0 in the bazelrc, it still gets 8.11.0

```
WARNING: For repository 'rules_java', the root module requires module version rules_java@8.5.0, but got rules_java@8.11.0 in the resolved dependency graph. Please update the version in your MODULE.bazel or set --check_direct_dependencies=off
```

- With `--incompatible_autoload_externally=-@com_google_protobuf` I get:

```
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.IllegalStateException: Symbol 'ProtoInfo' can't be removed, because it's still used by: java_binary
        at com.google.devtools.build.lib.packages.AutoloadSymbols.<init>(AutoloadSymbols.java:219)
        at com.google.devtools.build.lib.skyframe.SkyframeExecutor.preparePackageLoading(SkyframeExecutor.java:1618)
        at com.google.devtools.build.lib.skyframe.SkyframeExecutor.syncPackageLoading(SkyframeExecutor.java:2875)
        at com.google.devtools.build.lib.skyframe.SkyframeExecutor.sync(SkyframeExecutor.java:2830)
        at com.google.devtools.build.lib.skyframe.SequencedSkyframeExecutor.sync(SequencedSkyframeExecutor.java:285)
        at com.google.devtools.build.lib.runtime.CommandEnvironment.syncPackageLoading(CommandEnvironment.java:810)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:593)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:254)
        at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:606)
        at com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$0(GrpcServerImpl.java:676)
        at io.grpc.Context$1.run(Context.java:566)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
```

- With `--incompatible_autoload_externally=-@rules_python` I managed to build without issues
- With `--incompatible_autoload_externally=-@rules_shell` I managed to build without issues
- With `--incompatible_autoload_externally=-@rules_android` I managed to build without issues

If you are interested in reproduction you can use https://github.com/limdor/accu-2025/tree/0e39fce93de9e677fbb660ea45f8771cb439ae8d, you will just have to change the bazel version to the one that I mentioned.

**Comment by meteorcloudy** [comment]
This has landed in Bazel 9 and removed at HEAD at https://github.com/bazelbuild/bazel/commit/a3dc34c5
