### ISSUE TITLE
`--incompatible_use_plus_in_repo_names`

### ISSUE THREAD

**Issue by Wyverald** [bazelbuild/bazel#23127]
### Motivation

In https://github.com/bazelbuild/bazel/issues/22865, it was discovered that the `~` character currently used as a separator in canonical repo names can have significant performance impact on Windows.

We [reviewed all potential separators](https://github.com/bazelbuild/bazel/pull/23103#issuecomment-2251159312) and found that `+` could serve as a good replacement.

### Description

When set to true, the flag causes the canonical repo name format to use `+` wherever `~` is currently used. That is:

- For module repos: `$NAME+`
- For extension repos: `$MODULE+$EXTENSION_NAME+$APPARENT_REPO_NAME`

### Incompatible Flag

`--incompatible_use_plus_in_repo_names`

### Migration Guide

Ideally, people should have already not been depending on the canonical repo name format, as it was declared to be unstable.

But for those who have been parsing repo names, especially those relying on the existence of a `~` character, should try to switch to other alternatives:
- If you need access to the apparent repo name inside a repo rule, try passing in the apparent repo name as an explicit attr instead. (See https://github.com/bazelbuild/rules_java/commit/000587f210b73e45e646a9e459166fc56853ff6a and https://github.com/bazelbuild/rules_jvm_external/pull/1204 for example.)
- If you absolute can't avoid such parsing, try to accommodate for both `~` and `+`.

### In which Bazel LTS version will this incompatible change be enabled?

Bazel 8

### Additional Context

Note that in Bazel 8, this flag will be flipped to `true` by default, *and* the flag will immediately become a no-op (that is, setting it to `false` will have no effect). This is to avoid having to maintain the different repo name formats for another LTS cycle, especially as it was never a stable API to begin with.

### TODO List

- [x] Implement the incompatible change at Bazel HEAD and guard it behind a flag. (https://github.com/bazelbuild/bazel/pull/23103)
- [x] Backport the incompatible flag to the latest LTS release. (https://github.com/bazelbuild/bazel/pull/23141)
- [x] Test the incompatible change with [downstream projects](https://github.com/bazelbuild/continuous-integration/blob/master/docs/downstream-testing.md#bazel-downstream-testing) and inform broken projects.
- [x] Flip the incompatible flag at Bazel HEAD. (https://github.com/bazelbuild/bazel/pull/23098)
- [x] Delete the incompatible flag and the old behavior at Bazel HEAD. (https://github.com/bazelbuild/bazel/pull/23098)

**Comment by peakschris** [comment]
7.3.0rc1 is working well for us, fixes https://github.com/bazelbuild/bazel/issues/22865, thank you for your work on this!
