### ISSUE TITLE
--incompatible_bazel_test_exec_run_under

### ISSUE THREAD

**Issue by gregestren** [bazelbuild/bazel#23179]
### Motivation

`$ bazel test //:mytest --run_under=//:runner` will call `//:runner` on an exec machine. 

Bazel currently configures it for the target platform, which is incorrect. 

### Description

With this flag, `//:runner` is configured for the exec platform, where it actually runs.

### Incompatible Flag

--incompatible_bazel_test_exec_run_under

### Migration Guide

1) If you have a `$ bazel test //:mytest --run_under=//:runner` command, add `--incompatible_bazel_test_exec_run_under`.

If this fails, that means `//:runner` configures itself with target config information. This might be:

 - reads target platform properties from `--platforms`
 - reads `--define` or `--//foo` flags that don't propagate from the target to exec config
 - has a `select()` on any of the above.

Since `//:runner` is an execution tool, refactor it so it doesn't have target config dependencies. This may require moving target-configured deps (like some `data` binary) to `//:mytest` and having the test reference them from there.

### In which Bazel LTS version will this incompatible change be enabled?

Bazel 8

### Additional Context

Motivation: https://github.com/bazelbuild/bazel/issues/22624

### TODO List

- [x] Implement the incompatible change at Bazel HEAD and guard it behind a flag.
- [ ] Test the incompatible change with [downstream projects](https://github.com/bazelbuild/continuous-integration/blob/master/docs/downstream-testing.md#bazel-downstream-testing) and inform broken projects.
- [ ] Flip the incompatible flag at Bazel HEAD.
- [ ] Delete the incompatible flag and the old behavior at Bazel HEAD.

**Comment by armandomontanez** [comment]
For those watching at home, it looks like this didn't get flipped in Bazel 8.0.0.

**Comment by fmeum** [comment]
@gregestren In light of https://github.com/bazelbuild/bazel/pull/25123, I think that the `run_under` target should be configured for the exec platform of the `test` exec group, not the default exec group. Should we change that after that PR has been merged and before flipping this flag?

**Comment by gregestren** [comment]
@fmeum sounds reasonable.
