### ISSUE TITLE
Remove the Native Android Rules from Bazel

### ISSUE THREAD

**Issue by ahumesky** [bazelbuild/bazel#23199]
### Motivation

The Bazel Android rules have been converted to Starlark in https://github.com/bazelbuild/rules_android and https://github.com/bazelbuild/rules_android_ndk

The native Android rules are no longer maintained and should be deleted from Bazel.

### Description

The native Android rules will be removed from Bazel:

android_binary
mobile-install "classic"
android_library
aar_import
android_local_test
android_instrumentation_test
android_device
android_sdk_repository
android_ndk_repository
android_sdk

Their Starlark replacements are available at https://github.com/bazelbuild/rules_android and https://github.com/bazelbuild/rules_android_ndk

### Incompatible Flag

--incompatible_disable_native_android_rules

### Migration Guide

A Bazel blog post describing the migration in detail is forthcoming. In short, the Starlark Android rules are nearly 1:1 compatible with the native rules, and Bazel 8 will automatically load the Starlark version of the Android rules. Critical projects such as rules_jvm_external and tensorflow are migrating or are already migrated to the Starlark Android rules (https://github.com/bazelbuild/rules_jvm_external/pull/1149, https://github.com/tensorflow/tensorflow/pull/61809).

### In which Bazel LTS version will this incompatible change be enabled?

Bazel 8

### TODO List

Remove:
- [x] android_binary
- [x] mobile-install "classic"
- [x] android_library
- [x] aar_import
- [x] android_local_test
- [x] android_instrumentation_test
- [x] android_device
- [x] android_sdk_repository
- [x] android_ndk_repository
- [x] android_sdk

**Comment by ahumesky** [comment]
All the native Android rules have been removed in Bazel 8.0, and the tooling has been moved to rules_android.
