### ISSUE TITLE
Release 7.4.0 - October 2024

### ISSUE THREAD

**Issue by iancha1992** [bazelbuild/bazel#23271]
# Status of Bazel 7.4.0

-   Expected first release candidate date: 2024-10-10
-   Expected release date: 2024-10-22
-   [List of release blockers](https://github.com/bazelbuild/bazel/milestone/74)

To report a release-blocking bug, please add a comment with the text `@bazel-io flag` to the issue. A release manager will triage it and add it to the milestone.

To cherry-pick a mainline commit into 7.4.0, simply send a PR against the `release-7.4.0` branch.

**Task list:**

-   [x] Create release candidate
-   [x] Check downstream projects
-   [x] Create [draft release announcement](https://docs.google.com/document/d/1clxBctsjpei40wqqjwiU2EltTzsrf_kvZ4dJyZVqghM/edit)
-   [x] Push the release and notify package maintainers
-   [x] Update the documentation
-   [x] Update the [release page](https://github.com/bazelbuild/bazel/releases/)

**Comment by keith** [comment]
Would it be reasonable to do a RC of this release sooner? There have been a _lot_ of cherry picks that I would like to start testing with

**Comment by keertk** [comment]
@meteorcloudy @Wyverald thoughts on getting RC1 out before 10/7?

**Comment by keith** [comment]
Maybe matters less to me now that https://github.com/bazelbuild/bazel/commit/e43c933a99d204a270e4264e46a7a2d038d3aa7a  is in, but I'm sure more people would test a real RC

**Comment by Wyverald** [comment]
We're pushing back the rc1 date for 7.4.0 by two days (to 2024-10-09). In hindsight, planning 8.0.0rc1 and 7.4.0rc1 on the same date was maybe not the best idea :P

**Comment by iancha1992** [comment]
Bazel 7.4.0rc1 is now available for those that want to try it out.

You can download it from here: https://github.com/bazelbuild/bazel/releases/tag/7.4.0rc1
If you're using Bazelisk, you can point to this RC by setting USE_BAZEL_VERSION=7.4.0rc1.

Please test it out and report any issues [here](https://github.com/bazelbuild/bazel/issues) as soon as possible.
A draft of the release notes can be found [here](https://docs.google.com/document/d/1clxBctsjpei40wqqjwiU2EltTzsrf_kvZ4dJyZVqghM/edit?tab=t.0#heading=h.r3jngqrbyw0u).

Thanks!

**Comment by iancha1992** [comment]
Bazel 7.4.0rc2 is now available for those that want to try it out.

You can download it from here: https://github.com/bazelbuild/bazel/releases/tag/7.4.0rc2
If you're using Bazelisk, you can point to this RC by setting USE_BAZEL_VERSION=7.4.0rc2.

Please test it out and report any issues [here](https://github.com/bazelbuild/bazel/issues) as soon as possible.
A draft of the release notes can be found [here](https://docs.google.com/document/d/1clxBctsjpei40wqqjwiU2EltTzsrf_kvZ4dJyZVqghM/edit?tab=t.0#heading=h.r3jngqrbyw0u).

Thanks!

**Comment by iancha1992** [comment]
Bazel 7.4.0rc4 is now available for those that want to try it out.

You can download it from here: https://github.com/bazelbuild/bazel/releases/tag/7.4.0rc4
If you're using Bazelisk, you can point to this RC by setting USE_BAZEL_VERSION=7.4.0rc4.

Please test it out and report any issues [here](https://github.com/bazelbuild/bazel/issues) as soon as possible.
A draft of the release notes can be found [here](https://docs.google.com/document/d/1clxBctsjpei40wqqjwiU2EltTzsrf_kvZ4dJyZVqghM/edit?tab=t.0#heading=h.r3jngqrbyw0u).

Thanks!

**Comment by iancha1992** [comment]
Bazel 7.4.0 is now available: https://github.com/bazelbuild/bazel/releases/tag/7.4.0

cc: @excitoon, @vbatts for updating Scoop and Fedora packages. Thanks.
