### ISSUE TITLE
Release 8.0.0 - December 2024

### ISSUE THREAD

**Issue by keertk** [bazelbuild/bazel#23315]
# Status of Bazel 8.0.0

-   Expected first release candidate date: 2024-10-07
-   Expected final release candidate date: 2024-12-04
-   Expected release date: 2024-12-09
-   [List of release blockers](https://github.com/bazelbuild/bazel/milestone/77)

To report a release-blocking bug, please add a comment with the text `@bazel-io flag 8.0.0` to the issue. A release manager will triage it and add it to the milestone.

To cherry-pick a mainline commit into 8.0.0, simply send a PR against the `release-8.0.0` branch. 

**Task list:**

-   [x] Pick release baseline: https://github.com/bazelbuild/bazel/commit/d0285222b0060847d815d87d6757ca22e43ebd93
-   [x] Create release candidate: https://github.com/bazelbuild/bazel/releases/tag/8.0.0rc1
-   [x] Check downstream projects
-   [x] Create [draft release announcement](https://docs.google.com/document/d/187EF3dyCBz8ed3P9w7YTO5yPKU1pensNt3HA8be84Ms/edit#heading=h.vswxwomb18dc)
-   [ ] Send the release announcement PR for review
-   [x] Push the release and notify package maintainers
-   [ ] Update the documentation
-   [ ] Push the blog post
-   [ ] Update the [release page](https://github.com/bazelbuild/bazel/releases/)

**Comment by qMatr1xp** [comment]
> # Status of Bazel 8.0.0
> 
> -   Expected first release candidate date: 2024-10-07
> -   Expected final release candidate date: 2024-10-28
> -   Expected release date: 2024-11-04
> -   List of release blockers: (milestone to be created after the first RC)
> 
> To report a release-blocking bug, please add a comment with the text `@bazel-io flag 8.0.0` to the issue. A release manager will triage it and add it to the milestone.
> 
> To cherry-pick a mainline commit into 8.0.0, simply send a PR against the release-8.0.0 branch. (This branch will be created in October.)
> 
> **Task list:**
> 
> 
> 
> -   [ ] Pick release baseline: (to be done when creating the first RC)
> -   [ ] Create release candidate
> -   [ ] Check downstream projects
> -   [ ] Create [draft release announcement](https://docs.google.com/document/d/187EF3dyCBz8ed3P9w7YTO5yPKU1pensNt3HA8be84Ms/edit#heading=h.vswxwomb18dc)
> -   [ ] Send the release announcement PR for review
> -   [ ] Push the release and notify package maintainers
> -   [ ] Update the documentation
> -   [ ] Push the blog post
> -   [ ] Update the [release page](https://github.com/bazelbuild/bazel/releases/)
>

**Comment by iancha1992** [comment]
Bazel 8.0.0rc1 is now available for those that want to try it out.

You can download it from here: https://github.com/bazelbuild/bazel/releases/tag/8.0.0rc1
If you're using Bazelisk, you can point to this RC by setting USE_BAZEL_VERSION=8.0.0rc1.

Please test it out and report any issues [here](https://github.com/bazelbuild/bazel/issues) as soon as possible.
A draft of the release notes can be found [here](https://docs.google.com/document/d/187EF3dyCBz8ed3P9w7YTO5yPKU1pensNt3HA8be84Ms/edit#heading=h.vswxwomb18dc).

Thanks!

**Comment by criemen** [comment]
FWIW the `--incompatible_disallow_empty_glob` flag flip in 8.0 break `rules_dotnet`, reported here: https://github.com/bazel-contrib/rules_dotnet/issues/458
I suspect the downstream test suite doesn't contain a real-world project that uses `rules_dotnet`.

**Comment by brandjon** [comment]
I created three blocking issues, #23855, #23856, and #23857, but only the last one was automatically added to the release blocking hotlist. I'm guessing this might be because the first two contained the `@bazel-io flag 8.0.0` as part of the initial comment and not as a separate post, or because there wasn't enough newline separation from other content in the comment.

Can we get those two issues added to the blocker list, and possibly update the template for the next release-tracking issue to clarify the syntax?

**Comment by iancha1992** [comment]
@brandjon You've added them :)

**Comment by iancha1992** [comment]
Bazel 8.0.0rc2 is now available for those that want to try it out.

You can download it from here: https://github.com/bazelbuild/bazel/releases/tag/8.0.0rc2
If you're using Bazelisk, you can point to this RC by setting USE_BAZEL_VERSION=8.0.0rc2.

Please test it out and report any issues [here](https://github.com/bazelbuild/bazel/issues) as soon as possible.
An early draft of the release notes can be found [here](https://docs.google.com/document/d/187EF3dyCBz8ed3P9w7YTO5yPKU1pensNt3HA8be84Ms/edit#heading=h.vswxwomb18dc).

Thanks!

**Comment by Wyverald** [comment]
Status update, since people have been asking: we have been very busy trying to get rc3 out, and we're almost there! Currently looking like it'll come out tomorrow (22 Nov). That means that the final release is likely to be early December.

**Comment by iancha1992** [comment]
Bazel 8.0.0rc3 is now available for those that want to try it out.

You can download it from here: https://github.com/bazelbuild/bazel/releases/tag/8.0.0rc3
If you're using Bazelisk, you can point to this RC by setting USE_BAZEL_VERSION=8.0.0rc3.

Please test it out and report any issues [here](https://github.com/bazelbuild/bazel/issues) as soon as possible.
An early draft of the release notes can be found [here](https://docs.google.com/document/d/187EF3dyCBz8ed3P9w7YTO5yPKU1pensNt3HA8be84Ms/edit#heading=h.vswxwomb18dc).

Thanks!

**Comment by iancha1992** [comment]
Bazel 8.0.0rc4 is now available for those that want to try it out.

You can download it from here: https://github.com/bazelbuild/bazel/releases/tag/8.0.0rc4
If you're using Bazelisk, you can point to this RC by setting USE_BAZEL_VERSION=8.0.0rc4.

Please test it out and report any issues [here](https://github.com/bazelbuild/bazel/issues) as soon as possible.
An early draft of the release notes can be found [here](https://docs.google.com/document/d/187EF3dyCBz8ed3P9w7YTO5yPKU1pensNt3HA8be84Ms/edit#heading=h.vswxwomb18dc).

Thanks!

**Comment by iancha1992** [comment]
Bazel 8.0.0rc5 is now available for those that want to try it out.

You can download it from here: https://github.com/bazelbuild/bazel/releases/tag/8.0.0rc5
If you're using Bazelisk, you can point to this RC by setting USE_BAZEL_VERSION=8.0.0rc5.

Please test it out and report any issues [here](https://github.com/bazelbuild/bazel/issues) as soon as possible.
An early draft of the release notes can be found [here](https://docs.google.com/document/d/187EF3dyCBz8ed3P9w7YTO5yPKU1pensNt3HA8be84Ms/edit#heading=h.vswxwomb18dc).

Thanks!

**Comment by iancha1992** [comment]
Bazel 8.0.0rc6 is now available for those that want to try it out.

You can download it from here: https://github.com/bazelbuild/bazel/releases/tag/8.0.0rc6
If you're using Bazelisk, you can point to this RC by setting USE_BAZEL_VERSION=8.0.0rc6.

Please test it out and report any issues [here](https://github.com/bazelbuild/bazel/issues) as soon as possible.
An early draft of the release notes can be found [here](https://docs.google.com/document/d/187EF3dyCBz8ed3P9w7YTO5yPKU1pensNt3HA8be84Ms/edit#heading=h.vswxwomb18dc).

Thanks!

**Comment by iancha1992** [comment]
Bazel 8.0.0rc7 is now available for those that want to try it out.

You can download it from here: https://github.com/bazelbuild/bazel/releases/tag/8.0.0rc7
If you're using Bazelisk, you can point to this RC by setting USE_BAZEL_VERSION=8.0.0rc7.

Please test it out and report any issues [here](https://github.com/bazelbuild/bazel/issues) as soon as possible.
An early draft of the release notes can be found [here](https://docs.google.com/document/d/187EF3dyCBz8ed3P9w7YTO5yPKU1pensNt3HA8be84Ms/edit#heading=h.vswxwomb18dc).

Thanks!

**Comment by iancha1992** [comment]
Bazel 8.0.0rc8 is now available for those that want to try it out.

You can download it from here: https://github.com/bazelbuild/bazel/releases/tag/8.0.0rc8
If you're using Bazelisk, you can point to this RC by setting USE_BAZEL_VERSION=8.0.0rc8.

Please test it out and report any issues [here](https://github.com/bazelbuild/bazel/issues) as soon as possible.
An early draft of the release notes can be found [here](https://docs.google.com/document/d/187EF3dyCBz8ed3P9w7YTO5yPKU1pensNt3HA8be84Ms/edit#heading=h.vswxwomb18dc).

Thanks!

**Comment by iancha1992** [comment]
[Bazel 8.0](https://github.com/bazelbuild/bazel/releases/tag/8.0.0) is out! 🚀
Thank you to everyone that contributed to this major release!

cc [@excitoon](https://github.com/excitoon) [@vbatts](https://github.com/vbatts) for updating Scoop and Fedora packages. Thanks.

**Comment by iancha1992** [comment]
[Bazel 8.0](https://github.com/bazelbuild/bazel/releases/tag/8.0.0) is out! 🚀

cc [@excitoon](https://github.com/excitoon) [@vbatts](https://github.com/vbatts) for updating Scoop and Fedora packages. Thanks.
