### ISSUE TITLE
Release 8.0.1 - Jan 2025

### ISSUE THREAD

**Issue by iancha1992** [bazelbuild/bazel#24623]
# Status of Bazel 8.0.1

-   Expected first release candidate date: 2025-01-15
-   Expected release date: 2025-01-20
-   [List of release blockers](https://github.com/bazelbuild/bazel/milestone/81)

To report a release-blocking bug, please add a comment with the text `@bazel-io flag` to the issue. A release manager will triage it and add it to the milestone.

To cherry-pick a mainline commit into 8.0.1, simply send a PR against the `release-8.0.1` branch.

**Task list:**

-   [x] Create release candidate
-   [x] Check downstream projects
-   [x] Create [draft release announcement](https://docs.google.com/document/d/1clxBctsjpei40wqqjwiU2EltTzsrf_kvZ4dJyZVqghM/edit)
-   [x] Push the release and notify package maintainers
-   [x] Update the [release page](https://github.com/bazelbuild/bazel/releases/)

**Comment by iancha1992** [comment]
Bazel 8.0.1rc1 is now available for those that want to try it out.

You can download it from here: https://github.com/bazelbuild/bazel/releases/tag/8.0.1rc1
If you're using Bazelisk, you can point to this RC by setting USE_BAZEL_VERSION=8.0.1rc1.

Please test it out and report any issues [here](https://github.com/bazelbuild/bazel/issues) as soon as possible.
An early draft of the release notes can be found [here](https://docs.google.com/document/d/187EF3dyCBz8ed3P9w7YTO5yPKU1pensNt3HA8be84Ms/edit?tab=t.0#heading=h.f4uhofwcevdx).

Thanks!

**Comment by iancha1992** [comment]
Bazel 8.0.1 is now available: https://github.com/bazelbuild/bazel/releases/tag/8.0.1

cc: @excitoon, @vbatts for updating Scoop and Fedora packages. Thanks.
