### ISSUE TITLE
Release 8.1.0 - Feb 2025

### ISSUE THREAD

**Issue by iancha1992** [bazelbuild/bazel#24651]
# Status of Bazel 8.1.0

-   Expected first release candidate date: 2025-02-04
-   Expected release date: 2025-02-13
-   [List of release blockers](https://github.com/bazelbuild/bazel/milestone/82)

To report a release-blocking bug, please add a comment with the text `@bazel-io flag` to the issue. A release manager will triage it and add it to the milestone.

To cherry-pick a mainline commit into 8.1.0, simply send a PR against the `release-8.1.0` branch.

**Task list:**

-   [x] Create release candidate
-   [x] Check downstream projects
-   [x] Create [draft release announcement](https://docs.google.com/document/d/187EF3dyCBz8ed3P9w7YTO5yPKU1pensNt3HA8be84Ms/edit?tab=t.0#heading=h.1ldj0zgvx6cd)
-   [x] Push the release and notify package maintainers
-   [x] Update the documentation
-   [x] Update the [release page](https://github.com/bazelbuild/bazel/releases/)

**Comment by iancha1992** [comment]
Bazel 8.1.0rc1 is now available for those that want to try it out.

You can download it from here: https://github.com/bazelbuild/bazel/releases/tag/8.1.0rc1
If you're using Bazelisk, you can point to this RC by setting USE_BAZEL_VERSION=8.1.0rc1.

Please test it out and report any issues [here](https://github.com/bazelbuild/bazel/issues) as soon as possible.
An early draft of the release notes can be found [here](https://docs.google.com/document/d/187EF3dyCBz8ed3P9w7YTO5yPKU1pensNt3HA8be84Ms/edit?tab=t.0#heading=h.f4uhofwcevdx).

Thanks!

**Comment by iancha1992** [comment]
Bazel 8.1.0rc2 is now available for those that want to try it out.

You can download it from here: https://github.com/bazelbuild/bazel/releases/tag/8.1.0rc2
If you're using Bazelisk, you can point to this RC by setting USE_BAZEL_VERSION=8.1.0rc2.

Please test it out and report any issues [here](https://github.com/bazelbuild/bazel/issues) as soon as possible.
An early draft of the release notes can be found [here](https://docs.google.com/document/d/187EF3dyCBz8ed3P9w7YTO5yPKU1pensNt3HA8be84Ms/edit?tab=t.0#heading=h.gb9ncali4jpo).

Thanks!

**Comment by iancha1992** [comment]
Bazel 8.1.0rc3 is now available for those that want to try it out.

You can download it from here: https://github.com/bazelbuild/bazel/releases/tag/8.1.0rc3
If you're using Bazelisk, you can point to this RC by setting USE_BAZEL_VERSION=8.1.0rc3.

Please test it out and report any issues [here](https://github.com/bazelbuild/bazel/issues) as soon as possible.
An early draft of the release notes can be found [here](https://docs.google.com/document/d/187EF3dyCBz8ed3P9w7YTO5yPKU1pensNt3HA8be84Ms/edit?tab=t.0#heading=h.gb9ncali4jpo).

Thanks!

**Comment by yuzhy8701** [comment]
Hi @iancha1992 - could you help cherrypick https://github.com/bazelbuild/bazel/commit/0937e3543ec3fe904361244377baff315adf2091 to the 8.1 release?

I'm not sure if it's possible to cherrypick it to bazel 7 as well (since there doesn't seem to be a 7.5.1 release right now, and we should upgrade anyways).

**Comment by iancha1992** [comment]
Bazel 8.1.0 is now available: https://github.com/bazelbuild/bazel/releases/tag/8.1.0

cc: @excitoon, @vbatts for updating Scoop and Fedora packages. Thanks.
