### ISSUE TITLE
Release 7.5.0 - Jan 2025

### ISSUE THREAD

**Issue by iancha1992** [bazelbuild/bazel#24662]
# Status of Bazel 7.5.0

-   Expected first release candidate date: 2025-01-22
-   Expected release date: 2025-01-30
-   [List of release blockers](https://github.com/bazelbuild/bazel/milestone/80)

To report a release-blocking bug, please add a comment with the text `@bazel-io flag` to the issue. A release manager will triage it and add it to the milestone.

To cherry-pick a mainline commit into 7.5.0, simply send a PR against the `release-7.5.0` branch.

**Task list:**

-   [x] Create release candidate
-   [x] Check downstream projects
-   [x] Create [draft release announcement](https://docs.google.com/document/d/1clxBctsjpei40wqqjwiU2EltTzsrf_kvZ4dJyZVqghM/edit)
-   [ ] Push the release and notify package maintainers
-   [ ] Update the documentation
-   [ ] Update the [release page](https://github.com/bazelbuild/bazel/releases/)

**Comment by iancha1992** [comment]
Bazel 7.5.0rc2 is now available for those that want to try it out.

You can download it from here: https://github.com/bazelbuild/bazel/releases/tag/7.5.0rc2
If you're using Bazelisk, you can point to this RC by setting USE_BAZEL_VERSION=7.5.0rc2.

Please test it out and report any issues [here](https://github.com/bazelbuild/bazel/issues) as soon as possible.
A draft of the release notes can be found [here](https://docs.google.com/document/d/1clxBctsjpei40wqqjwiU2EltTzsrf_kvZ4dJyZVqghM/edit?tab=t.0#heading=h.arxf5lry3z2a).

Thanks!

**Comment by fmeum** [comment]
@iancha1992 Sorry for noticing this so late, but I just submitted https://github.com/bazelbuild/bazel/pull/25040 to fix a Bazel 7 regression.

**Comment by timothyklim** [comment]
JDK 24 will be released in March, can bazel 7.5 support it through update of error-prone https://github.com/google/error-prone/pull/4642 ? 8.0.0 already updated error-prone dep.

**Comment by iancha1992** [comment]
Bazel 7.5.0rc3 is now available for those that want to try it out.

You can download it from here: https://github.com/bazelbuild/bazel/releases/tag/7.5.0rc3
If you're using Bazelisk, you can point to this RC by setting USE_BAZEL_VERSION=7.5.0rc3.

Please test it out and report any issues [here](https://github.com/bazelbuild/bazel/issues) as soon as possible.
A draft of the release notes can be found [here](https://docs.google.com/document/d/1clxBctsjpei40wqqjwiU2EltTzsrf_kvZ4dJyZVqghM/edit?tab=t.0#heading=h.arxf5lry3z2a).

Thanks!

**Comment by iancha1992** [comment]
Bazel 7.5.0 is now available: https://github.com/bazelbuild/bazel/releases/tag/7.5.0

cc: @excitoon, @vbatts for updating Scoop and Fedora packages. Thanks.
