### ISSUE TITLE
Release - January 2018 - Target RC date: 2018-01-09 - name: 0.10.0

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#3958]
Release tracking bug for January 2018:

* Target cut should be 2nd of January (first business day of January) but since it is close to holidays we need to check with whoever is going to be RM.
* Name: 0.10.0

RM if we follow the rotation should be @philwo: can you take it?

**Comment by iirina** [comment]
I am looking for a proper RC. Current situation: 
* Latest Blaze release was on 18.12.2017, which is too old for a Bazel RC baseline.
* Latest Bazel nightly fails due to Jenkins error (#4397). 

I think the best approach is to fix the Bazel nightly and try to cut a RC from there.

**Comment by iirina** [comment]
I rebuilt the [nightly](https://ci.bazel.build/view/Bazel%20bootstrap%20and%20maintenance/job/bazel/job/nightly/182/) just to see if the error persists.

**Comment by iirina** [comment]
There are problems with the CI and there is no reliable way of cutting a RC today. @philwo is working on updating Jenkins. I will update this issue when the situation improves or when I have an ETA.

**Comment by iirina** [comment]
We have a [nightly](https://ci.bazel.build/view/Dashboard/job/bazel/job/nightly/). I cut a RC based on that:
```
[...]/release.sh create 0.10.0 22c2f9a7722e8c8b7fdf8f5d30a40f1c4118e993
Created 0.10.0rc1 on branch release-0.10.0
```
Next step: identify the breakages/failures in the nightly and mark them as release blockers.

**Comment by iirina** [comment]
The release [push job](https://ci.bazel.build/job/bazel/job/release/895) failed:
```
[release] Running shell script
scripts/ci/build.sh: line 161: /opt/data/hoedown/hoedown: No such file or directory
```

Looking into it.

**Comment by iirina** [comment]
[Replayed the job](https://ci.bazel.build/job/bazel/job/release/898/) and it finished successfully. [RC1](https://releases.bazel.build/0.10.0/rc1/index.html) is available for testing. I will now create issues for the failing projects.

**Comment by iirina** [comment]
Currently known release blockers:

- [ ] CI rules_nodejs is failing with bazel 0.10.0 RC1 #4421
- [ ] CI BUILD_file_generator is failing with bazel 0.10.0 RC1 #4422
- [ ] CI bazel-integration-testing is failing with bazel 0.10.0 RC1 #4423
- [ ] CI rules_docker is failing with bazel 0.10.0 RC1 #4424
- [ ] CI projects are failing with bazel 0.10.0 RC1 due to wrongly identifying the current Bazel version #4425
- [ ] CI rules_go is failing with bazel 0.10.0 RC1 #4426
- [ ] CI rules_k8s fails with bazel 0.10.0 RC1 #4427
- [ ] CI intellij is failing with bazel 0.10.0 RC1 #4428
- [ ] CI bazel tests are failing with bazel 0.10.0 RC1 #4429
- [ ] CI glog is failing with bazel 0.10.0 RC1 #4430
- [ ] CI tf_models_syntaxnet is failing with bazel 0.10.0 RC1 #4431

@jin Can you please triage them? I suspect that after fixing #4425 more issues will surface.

**Comment by buchgr** [comment]
@iirina this is also a regression from 0.9.0 that needs to be fixed https://github.com/bazelbuild/bazel/issues/4343

**Comment by pmuetschard** [comment]
Would it be possible to cherry pick f6ca78808722c8c119affdb33400838ee92d44b6 into 0.10.0? Without it Android build rules on Windows are broken.

(Excuse the lousy change description of the commit. I've added a comment at the bottom of the change.)

**Comment by iirina** [comment]
@pmuetschard if it fixes a regression issue from previous releases then it can be cherry picked.

**Comment by pmuetschard** [comment]
@iirina, yes it fixes a regression introduced by https://github.com/bazelbuild/bazel/commit/146bb7dc5da87d067e463508c6ae5462bbd3d511

**Comment by iirina** [comment]
Next RC will be cut on Monday.

**Comment by laszlocsomor** [comment]
Fix for rules_nodejs: https://github.com/bazelbuild/bazel/commit/e5436745e1732f5e43fc55f0deb5b19e23ce8524

**Comment by petemounce** [comment]
https://chocolatey.org/packages/bazel/0.10.0-rc1 is available.

**Comment by iirina** [comment]
I created and pushed the new RC.

```
[...]/release.sh create 0.10.0 f6ca78808722c8c119affdb33400838ee92d44b6 65c13dd5a4c1b4b5a072f7680b8f1cf3c5079b52 e5436745e1732f5e43fc55f0deb5b19e23ce8524
From sso://bazel/bazel
 * branch                master     -> FETCH_HEAD
Creating new release branch release-0.10.0 for release 0.10.0
Switched to a new branch 'release-0.10.0'
Applying cherry-picks
  Cherry-picking 65c13dd5a4c1b4b5a072f7680b8f1cf3c5079b52
The previous cherry-pick is now empty, possibly due to conflict resolution.
If you wish to commit it anyway, use:

    git commit --allow-empty

Otherwise, please use 'git reset'
Failed to cherry-pick 65c13dd5a4c1b4b5a072f7680b8f1cf3c5079b52. please resolve the conflict and exit.
  Use 'git cherry-pick --abort; exit' to abort the cherry-picks.
  Use 'git cherry-pick --continue; exit' to resolve the conflict.
```

```
git commit --allow-empty; exit
[release-0.10.0 85ede7fe2] Fix StreamResourceLeak error
 Author: Liam Miller-Cushon <cushon@google.com>
 Date: Wed Jan 10 08:00:00 2018 -0800
exit
  Cherry-picking e5436745e1732f5e43fc55f0deb5b19e23ce8524
Creating release notes
Created 0.10.0rc1 on branch release-0.10.0.
```

```
[...]/release.sh push
```

There was something I didn't understand when creating the RC: e5436745e1732f5e43fc55f0deb5b19e23ce8524 couldn't be cherry picked because it was seen as empty.

New CI release job is [here](https://ci.bazel.build/job/bazel/job/release/976/).

**Comment by iirina** [comment]
OK, I see now. I forgot to add the baseline when creating the new RC. Will redo everything...

**Comment by iirina** [comment]
Re-created RC2:

```
release.sh create 0.10.0 22c2f9a7722e8c8b7fdf8f5d30a40f1c4118e993 f6ca78808722c8c119affdb33400838ee92d44b6 65c13dd5a4c1b4b5a072f7680b8f1cf3c5079b52 e5436745e1732f5e43fc55f0deb5b19e23ce8524
remote: Counting objects: 7114, done        
remote: Finding sources: 100% (13/13)           
remote: Total 13 (delta 7), reused 13 (delta 7)        
From sso://bazel/bazel
 * branch                master     -> FETCH_HEAD
Creating new release branch release-0.10.0 for release 0.10.0
Reset branch 'release-0.10.0'
Applying cherry-picks
  Cherry-picking f6ca78808722c8c119affdb33400838ee92d44b6
  Cherry-picking 65c13dd5a4c1b4b5a072f7680b8f1cf3c5079b52
  Cherry-picking e5436745e1732f5e43fc55f0deb5b19e23ce8524
Creating release notes
Created 0.10.0rc2 on branch release-0.10.0.
```

and pushed it:
`[...]/release.sh push`

Aborted previous CI job (976[](https://ci.bazel.build/job/bazel/job/release/976/)).
New CI release job is [978](https://ci.bazel.build/job/bazel/job/release/978/).

**Comment by iirina** [comment]
[RC2](https://releases.bazel.build/0.10.0/rc2/index.html) is now available for testing.

**Comment by iirina** [comment]
Some more cherry picks that are needed:

- 22ccdd1ebe1dc495e05d894a3325f6b05e681fb3 -> was also used to fix #4422

ALL Cherry picks needed for RC3:
- f6ca78808722c8c119affdb33400838ee92d44b6
- 65c13dd5a4c1b4b5a072f7680b8f1cf3c5079b52
- e5436745e1732f5e43fc55f0deb5b19e23ce8524
- 22ccdd1ebe1dc495e05d894a3325f6b05e681fb3

**Comment by buchgr** [comment]
You can remove #4343 as a release blocker. The change was intentional and more discussion is needed.

**Comment by iirina** [comment]
@buchgr Noted.

I replayed the CI release job ([1027](https://ci.bazel.build/job/bazel/job/release/1027/)) to figure out what blockers were fixed without cherry picks.

**Comment by dslomov** [comment]
#4474 is a release blocker

**Comment by iirina** [comment]
I cut RC3 today:

```
release.sh create 0.10.0 22c2f9a7722e8c8b7fdf8f5d30a40f1c4118e993 f6ca78808722c8c119affdb33400838ee92d44b6 65c13dd5a4c1b4b5a072f7680b8f1cf3c5079b52 e5436745e1732f5e43fc55f0deb5b19e23ce8524 22ccdd1ebe1dc495e05d894a3325f6b05e681fb3 96c654d43eb2906177325cbc2fc2b1e90dbcc792

From sso://bazel/bazel
 * branch                master     -> FETCH_HEAD
Creating new release branch release-0.10.0 for release 0.10.0
Switched to and reset branch 'release-0.10.0'
Applying cherry-picks
  Cherry-picking f6ca78808722c8c119affdb33400838ee92d44b6
  Cherry-picking 65c13dd5a4c1b4b5a072f7680b8f1cf3c5079b52
  Cherry-picking e5436745e1732f5e43fc55f0deb5b19e23ce8524
  Cherry-picking 22ccdd1ebe1dc495e05d894a3325f6b05e681fb3
  Cherry-picking 96c654d43eb2906177325cbc2fc2b1e90dbcc792
Creating release notes
Created 0.10.0rc3 on branch release-0.10.0.
```

CI [release job](https://ci.bazel.build/view/Bazel%20bootstrap%20and%20maintenance/job/bazel/job/release/1046)

New TODO list:

* Rollback the culprit of #4474 (2aeaeba66857c561dd6d63c79a213f1cabc3650d)

**Comment by petemounce** [comment]
https://chocolatey.org/packages/bazel/0.10.0-rc3 has been pushed.

**Comment by iirina** [comment]
Replayed CI release job to rule out some flakiness: [1048](https://ci.bazel.build/view/Bazel%20bootstrap%20and%20maintenance/job/bazel/job/release/)

**Comment by iirina** [comment]
Replayed once more [(1066)](https://ci.bazel.build/view/Bazel%20bootstrap%20and%20maintenance/job/bazel/job/release/1066/) to see if #4474 is fixed. TF is green on the CI.

**Comment by dslomov** [comment]
Please cherry-pick  f0bec36 (fix for #4474)

**Comment by iirina** [comment]
Created RC4:

```
release.sh create 0.10.0 22c2f9a7722e8c8b7fdf8f5d30a40f1c4118e993 f6ca78808722c8c119affdb33400838ee92d44b6 65c13dd5a4c1b4b5a072f7680b8f1cf3c5079b52 e5436745e1732f5e43fc55f0deb5b19e23ce8524 22ccdd1ebe1dc495e05d894a3325f6b05e681fb3 96c654d43eb2906177325cbc2fc2b1e90dbcc792 f0bec36864f10370cbbda4caa8beac2e0c5ee45b

From sso://bazel/bazel
 * branch                master     -> FETCH_HEAD
Creating new release branch release-0.10.0 for release 0.10.0
Switched to and reset branch 'release-0.10.0'
Applying cherry-picks
  Cherry-picking f6ca78808722c8c119affdb33400838ee92d44b6
  Cherry-picking 65c13dd5a4c1b4b5a072f7680b8f1cf3c5079b52
  Cherry-picking e5436745e1732f5e43fc55f0deb5b19e23ce8524
  Cherry-picking 22ccdd1ebe1dc495e05d894a3325f6b05e681fb3
  Cherry-picking 96c654d43eb2906177325cbc2fc2b1e90dbcc792
  Cherry-picking f0bec36864f10370cbbda4caa8beac2e0c5ee45b
Creating release notes
Created 0.10.0rc4 on branch release-0.10.0.
```

[CI job](https://ci.bazel.build/job/bazel/job/release/1071/)

**Comment by iirina** [comment]
The release job failed for RC4 and it was not pushed. Investigating now.

**Comment by iirina** [comment]
RC4 is available for testing: https://releases.bazel.build/0.10.0/rc4/index.html

**Comment by iirina** [comment]
RC4 failures:

- [ ] bazel-integration-testing  167
- [ ] TensorFlow_Serving  369 -> Needs update of bazel version checking function.
- [x] intellij  369 -> Related to https://github.com/bazelbuild/intellij/issues/215 (JetBrains has changed their plugin URLs from https://download.plugins.jetbrains.com to https://plugins.jetbrains.com/files.) -> Not a Bazel issue.
- [ ] rules_nodejs  190
- [ ] rules_webtesting  28
- [ ] rules_closure  372
- [ ] tf_models_syntaxnet  370
- [ ] bazel-tests  453

**Comment by iirina** [comment]
Verified that RC4 can bootstrap on Windows. Build was successful.

**Comment by petemounce** [comment]
https://chocolatey.org/packages/bazel/0.10.0-rc4 has been pushed.

**Comment by cushon** [comment]
@iirina can you cherry-pick 860af5be10b6bad68144d9d2d34173e86b40268c for #4483?

**Comment by iirina** [comment]
@cushon Done.

Created RC5:
```
release.sh create 0.10.0 22c2f9a7722e8c8b7fdf8f5d30a40f1c4118e993 f6ca78808722c8c119affdb33400838ee92d44b6 65c13dd5a4c1b4b5a072f7680b8f1cf3c5079b52 e5436745e1732f5e43fc55f0deb5b19e23ce8524 22ccdd1ebe1dc495e05d894a3325f6b05e681fb3 96c654d43eb2906177325cbc2fc2b1e90dbcc792 f0bec36864f10370cbbda4caa8beac2e0c5ee45b 860af5be10b6bad68144d9d2d34173e86b40268c

Creating new release branch release-0.10.0 for release 0.10.0
Switched to and reset branch 'release-0.10.0'
Applying cherry-picks
  Cherry-picking f6ca78808722c8c119affdb33400838ee92d44b6
  Cherry-picking 65c13dd5a4c1b4b5a072f7680b8f1cf3c5079b52
  Cherry-picking e5436745e1732f5e43fc55f0deb5b19e23ce8524
  Cherry-picking 22ccdd1ebe1dc495e05d894a3325f6b05e681fb3
  Cherry-picking 96c654d43eb2906177325cbc2fc2b1e90dbcc792
  Cherry-picking f0bec36864f10370cbbda4caa8beac2e0c5ee45b
  Cherry-picking 860af5be10b6bad68144d9d2d34173e86b40268c
Creating release notes
Created 0.10.0rc5 on branch release-0.10.0.

release.sh push
```

CI job is [1108](https://ci.bazel.build/job/bazel/job/release/1108/)

**Comment by iirina** [comment]
Release job failed again ([piepline](https://ci.bazel.build/blue/organizations/jenkins/bazel%2Frelease/detail/release/1108/pipeline)) with the same error as the first release job for RC4:

```
ERROR: /home/ci/workspace/bazel/release/scripts/packages/debian/BUILD:98:1: Executing genrule //scripts/packages/debian:generate-changelog-file failed (Exit 1): bash failed: error executing command 

  (cd /home/ci/.cache/bazel/_bazel_ci/f17546af8fc3afba783542703df2c075/execroot/io_bazel && \

  exec env - \

    PATH=/home/ci/node/node-v6.9.1-linux-x64/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/bin:/usr/local/bin \

  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; python scripts/packages/debian/convert_changelog.py bazel-out/volatile-status.txt ./CHANGELOG.md bazel-out/k8-fastbuild/genfiles/scripts/packages/debian/changelog')
```

New CI release job is [1110](https://ci.bazel.build/job/bazel/job/release/1110/). Last time the failure went away after replaying the job, probably now it's the same. *sigh*

**Comment by laszlocsomor** [comment]
The failing script was `scripts/packages/debian/convert_changelog.py`, so let's /cc @meteorcloudy

**Comment by iirina** [comment]
RC5 is available for testing:  https://releases.bazel.build/0.10.0/rc5/index.html.

**Comment by meteorcloudy** [comment]
I wrote this script a long time ago, let me take a look.

**Comment by meteorcloudy** [comment]
@iirina @laszlocsomor It seems this script has changed a lot in https://github.com/bazelbuild/bazel/commit/332b61f416855eb5938a226eed7787473487a268, I don't know exactly what's causing the flakiness, but I can make this script more robust. Will send a change.

**Comment by iirina** [comment]
Failing jobs of RC5:

- [x] rules_webtesting: failing tests. *not* blocking the release.
- [x] rules_nodejs: #4501 Fails on Windows. Not a regression issue (can be reproduced with bazel 0.9.0).
- [ ] tf_models_syntaxnet
- [x] rules_closure: failing tests. *not* blocking the release.
- [ ] bazel-tests: one flaky test failing (`test_failed_build`) and another failed test (`text.xml` see #4497).

**Comment by iirina** [comment]
One more cherry pick: 2e631c99495f75270d2639542cefb531ec262d67 (fixes #4303).

**Comment by iirina** [comment]
Pushed RC6. It should be the last RC \o/

```
release.sh create 0.10.0 22c2f9a7722e8c8b7fdf8f5d30a40f1c4118e993 f6ca78808722c8c119affdb33400838ee92d44b6 65c13dd5a4c1b4b5a072f7680b8f1cf3c5079b52 e5436745e1732f5e43fc55f0deb5b19e23ce8524 22ccdd1ebe1dc495e05d894a3325f6b05e681fb3 96c654d43eb2906177325cbc2fc2b1e90dbcc792 f0bec36864f10370cbbda4caa8beac2e0c5ee45b 860af5be10b6bad68144d9d2d34173e86b40268c 2e631c99495f75270d2639542cefb531ec262d67 5bfa5844d0d16d71e88002956e88402bfec88ef7

Creating new release branch release-0.10.0 for release 0.10.0
Switched to and reset branch 'release-0.10.0'
Applying cherry-picks
  Cherry-picking f6ca78808722c8c119affdb33400838ee92d44b6
  Cherry-picking 65c13dd5a4c1b4b5a072f7680b8f1cf3c5079b52
  Cherry-picking e5436745e1732f5e43fc55f0deb5b19e23ce8524
  Cherry-picking 22ccdd1ebe1dc495e05d894a3325f6b05e681fb3
  Cherry-picking 96c654d43eb2906177325cbc2fc2b1e90dbcc792
  Cherry-picking f0bec36864f10370cbbda4caa8beac2e0c5ee45b
  Cherry-picking 860af5be10b6bad68144d9d2d34173e86b40268c
  Cherry-picking 2e631c99495f75270d2639542cefb531ec262d67
  Cherry-picking 5bfa5844d0d16d71e88002956e88402bfec88ef7
Creating release notes
Created 0.10.0rc6 on branch release-0.10.0.

release.sh push
```

CI release job is [1127](https://ci.bazel.build/view/Bazel%20bootstrap%20and%20maintenance/job/bazel/job/release/1127/).

**Comment by iirina** [comment]
...aaaand the job failed. Pipelineis [here](https://ci.bazel.build/blue/organizations/jenkins/bazel%2Frelease/detail/release/1127/pipeline/22).

First error on Linux (cc: @meteorcloudy)
```
Traceback (most recent call last):

  File "scripts/packages/debian/convert_changelog.py", line 89, in <module>

    main(sys.argv[1], sys.argv[2], sys.argv[3])

  File "scripts/packages/debian/convert_changelog.py", line 49, in main

    parts[2], "(%Y-%m-%d)").strftime("%a, %d %b %Y %H:%M:%S +0100")

  File "/usr/lib/python2.7/_strptime.py", line 325, in _strptime

    (data_string, format))

ValueError: time data 'TMPDIR' does not match format '(%Y-%m-%d)'
```

Second error on Darwin (cc: @philwo):
```
[release] Running shell script

+ /Users/ci/.bazel/latest/binary/bazel --bazelrc=/Users/ci/workspace/bazel/release/bazel.bazelrc build //src:bazel //scripts/packages

/Users/ci/workspace/bazel/release@tmp/durable-a87fdb8a/script.sh: line 2: /Users/ci/.bazel/latest/binary/bazel: No such file or directory

script returned exit code 1
```



New release job [1128](https://ci.bazel.build/view/Bazel%20bootstrap%20and%20maintenance/job/bazel/job/release/1128/).

**Comment by philwo** [comment]
I... might have "accidentally" canceled that job because I wanted to upgrade all the Mac Pros to macOS 10.13.3. 😅

**Comment by iirina** [comment]
The new job went through and RC6 is available for testing at https://releases.bazel.build/0.10.0/rc6/index.html.

**Comment by petemounce** [comment]
https://chocolatey.org/packages/bazel/0.10.0-rc6 has been pushed.

**Comment by iirina** [comment]
There were some problems with the Darwin machines, I will replay the job again. This will send another email to bazel-discuss, but there are too many jobs to replay individually.

New job is [1132](https://ci.bazel.build/view/Bazel%20bootstrap%20and%20maintenance/job/bazel/job/release/1132/).

**Comment by iirina** [comment]
New release blocker #4514

**Comment by buchgr** [comment]
@iirina #4514 is not a release blocker.

**Comment by iirina** [comment]
@buchgr Good to hear that. Thanks :smiley:

**Comment by iirina** [comment]
Failing jobs of RC6:

- [ ] rules_scala: JRE fatal error SIGBUS. 
- I cleaned up all the Ubuntu VMs.
- [Replayed job ](https://ci.bazel.build/blue/organizations/jenkins/Global%2Frules_scala/detail/rules_scala/377/pipeline)
- is now green 
- [ ] intellij 
- [ ] bazel-tests-remote
- [ ] bazel-tests  
- [ ] rules_webtesting
- [ ] rules_closure 
- [ ] tf_models_syntaxnet  
- [ ] rules_go: 
- [Blue Ocean](https://ci.bazel.build/blue/organizations/jenkins/Global%2Frules_go/detail/rules_go/375/pipeline/) shows one failing test - will investigate

**Comment by iirina** [comment]
New cherry pick 6cc2ad8676d1ae0542b351a07a05ddbe5efac165 (see #4529)

**Comment by iirina** [comment]
Created and pushed RC7
```
release.sh create 0.10.0 22c2f9a7722e8c8b7fdf8f5d30a40f1c4118e993 f6ca78808722c8c119affdb33400838ee92d44b6 65c13dd5a4c1b4b5a072f7680b8f1cf3c5079b52 e5436745e1732f5e43fc55f0deb5b19e23ce8524 22ccdd1ebe1dc495e05d894a3325f6b05e681fb3 96c654d43eb2906177325cbc2fc2b1e90dbcc792 f0bec36864f10370cbbda4caa8beac2e0c5ee45b 860af5be10b6bad68144d9d2d34173e86b40268c 2e631c99495f75270d2639542cefb531ec262d67 5bfa5844d0d16d71e88002956e88402bfec88ef7 6cc2ad8676d1ae0542b351a07a05ddbe5efac165

release.sh push
```

CI job is [1180](https://ci.bazel.build/view/Bazel%20bootstrap%20and%20maintenance/job/bazel/job/release/1180/)

**Comment by iirina** [comment]
[Pipeline](https://ci.bazel.build/blue/organizations/jenkins/bazel%2Frelease/detail/release/1180/pipeline/22) failed again due to `convert_changelog.py`. I filed #4530.

**Comment by iirina** [comment]
There are no more release blockers that I am aware of. If none surfaces today or tomorrow, Bazel 0.10.0 will be released on Wednesday.

**Comment by iirina** [comment]
New cherry pick 40c757f4ab90214f95935672532a495c4551490a for release blocker #4537.

**Comment by iirina** [comment]
Pushed RC8:
```
release.sh create 0.10.0 22c2f9a7722e8c8b7fdf8f5d30a40f1c4118e993 f6ca78808722c8c119affdb33400838ee92d44b6 65c13dd5a4c1b4b5a072f7680b8f1cf3c5079b52 e5436745e1732f5e43fc55f0deb5b19e23ce8524 22ccdd1ebe1dc495e05d894a3325f6b05e681fb3 96c654d43eb2906177325cbc2fc2b1e90dbcc792 f0bec36864f10370cbbda4caa8beac2e0c5ee45b 860af5be10b6bad68144d9d2d34173e86b40268c 2e631c99495f75270d2639542cefb531ec262d67 5bfa5844d0d16d71e88002956e88402bfec88ef7 6cc2ad8676d1ae0542b351a07a05ddbe5efac165 40c757f4ab90214f95935672532a495c4551490a

release.sh push
```
CI release job is [1228](https://ci.bazel.build/view/Bazel%20bootstrap%20and%20maintenance/job/bazel/job/release/1228/).

**Comment by iirina** [comment]
I did a bad merge and I had to re-do RC8. The same commands as before.

CI release job is [1234](https://ci.bazel.build/view/Bazel%20bootstrap%20and%20maintenance/job/bazel/job/release/1234/) (lucky number?).

**Comment by iirina** [comment]
RC8 available for testing https://releases.bazel.build/0.10.0/rc8/index.html

**Comment by iirina** [comment]
RC8 looks good. I propose no more cherry picks, even if further regressions will be found. Bazel 0.11.0 RC1 will be cut tomorrow, so further regressions should be cherry picked for 0.11.0. This way Bazel 0.10.0 can be released before Bazel 0.11.0 RC1 is cut and avoid dealing with 2 releases at the same time.

**Comment by iirina** [comment]
bazel 0.10.0 is now released.

@petemounce @ilovezfs Can you update Chocolatey and HomeBrew please?

**Comment by ilovezfs** [comment]
https://github.com/Homebrew/homebrew-core/pull/23560

**Comment by ilovezfs** [comment]
shipped.

**Comment by petemounce** [comment]
Shipped:

* https://chocolatey.org/packages/bazel/0.10.0-rc7
* https://chocolatey.org/packages/bazel/0.10.0-rc8
* https://chocolatey.org/packages/bazel/0.10.0

Also, a bit of progress with #4049 via #4559.

**Comment by ola-rozenfeld** [comment]
Cherrypick candidate: https://github.com/bazelbuild/bazel/commit/56aeb04a064218b845ecc193d530c341c6ec854d

**Comment by iirina** [comment]
Thanks @ola-rozenfeld!

I'll create a patch release Monday (12 Dec).

**Comment by iirina** [comment]
Creating & pushing RC1 for patch release `bazel 0.10.1`:

```
release.sh create 0.10.1 22c2f9a7722e8c8b7fdf8f5d30a40f1c4118e993 f6ca78808722c8c119affdb33400838ee92d44b6 65c13dd5a4c1b4b5a072f7680b8f1cf3c5079b52 e5436745e1732f5e43fc55f0deb5b19e23ce8524 22ccdd1ebe1dc495e05d894a3325f6b05e681fb3 96c654d43eb2906177325cbc2fc2b1e90dbcc792 f0bec36864f10370cbbda4caa8beac2e0c5ee45b 860af5be10b6bad68144d9d2d34173e86b40268c 2e631c99495f75270d2639542cefb531ec262d67 5bfa5844d0d16d71e88002956e88402bfec88ef7 6cc2ad8676d1ae0542b351a07a05ddbe5efac165 40c757f4ab90214f95935672532a495c4551490a 56aeb04a064218b845ecc193d530c341c6ec854d

Created 0.10.1rc1 on branch release-0.10.1.

release.sh push
```

CI job is lucky number [1450](https://ci.bazel.build/view/Bazel%20bootstrap%20and%20maintenance/job/bazel/job/release/1450/)

**Comment by petemounce** [comment]
Pushed 0.10.1 to https://chocolatey.org/packages/bazel/0.10.1
