### ISSUE TITLE
Release - March 2018 - Target RC date: 2018-04-02 - name: 0.13.0

### ISSUE THREAD

**Issue by dslomov** [bazelbuild/bazel#4583]

**Comment by dslomov** [comment]
@meteorcloudy lmk if you are not available on these dates

**Comment by lfpino** [comment]
https://github.com/bazelbuild/bazel/issues/4928 may be a blocker for this release.

**Comment by dslomov** [comment]
We will be cutting RC approximately on April 7th /cc @philwo

**Comment by meteorcloudy** [comment]
I can do it by Friday.

**Comment by meteorcloudy** [comment]
There are some jobs failing with Bazel@HEAD, but not with 0.11.0, we need to fix them

- [ ] [bazel-skylib (mac)](https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/187#16099227-bc58-4f4f-9fae-9d5f995d1d63)
- [ ] [protobuf (mac)](https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/187#2531d286-9702-4146-917d-c475a4dd8d56)
- [ ] [rules_nodejs (windows)](https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/187#b8548b2f-c2c0-48cf-aae1-46c4f63077e3)
- [ ] [rules_docker (all)](https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/187#18a28f75-ab38-45fd-b9df-eea7c7b46233)
- [ ] [rules_python (all)](https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/187#1048a27e-383a-4424-ac05-3ec0060ca7b2)
- [ ] [rules_typescript (all)](https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/187#78c96382-750d-4ee8-a700-36513b3dd056)

Ping the current Sheriff @vladmos 

If they cannot be fixed in time, I will cut the release and cherry-pick the fix later.

**Comment by meteorcloudy** [comment]
The mac failures are due to https://github.com/bazelbuild/bazel/issues/4751, so I marked it as a release blocker.

**Comment by vladmos** [comment]
rules_python: there's an issue https://github.com/bazelbuild/rules_python/issues/67 and a pull request https://github.com/bazelbuild/rules_python/pull/83 that's supposed to fix it.
rules_typescript: red due to a remote caching problem, there's an existing issue for it: https://github.com/bazelbuild/bazel/issues/4928 . Not sure if it's considered as a release blocker (@buchgr)
rules_docker: a pending issue: https://github.com/bazelbuild/rules_docker/issues/363
rules_nodejs on windows: a pending issue: https://github.com/bazelbuild/rules_nodejs/issues/165

**Comment by meteorcloudy** [comment]
@vladmos Thanks Vlad for summarizing all these!
Seems like most of fixes are not on Bazel side, except #4751 and #4928 (possibly)
They I'll cut a release based on yesterday's nightly, that is fdee70e6e39b74bfd9144b1e350d2d8806386e05

**Comment by meteorcloudy** [comment]
Release candidate 1 has been successfully cut, branch has been pushed (https://github.com/bazelbuild/bazel/tree/release-0.13.0)

**Comment by petemounce** [comment]
0.13.0-rc1 is available on chocolatey.

**Comment by laszlocsomor** [comment]
The release notes contains entries from the 0.12.0 release notes. I believe the release notes generator script is confused, because the last release was 0.11, not 0.12.

Also, there are duplicate entries, "None" entries, and some entries that were manually removed from the 0.12.0 release notes.

Please remove the following entries:

> - python,runfiles: You can now depend on
>    `@bazel_tools//tools/runfiles:py-runfiles` to get a
>    platform-independent runfiles library for Python. See DocString
>    of
>    https://github.com/bazelbuild/bazel/blob/master/src/tools/runfiles
>    /runfiles.py for usage information.
>  ...
>  - The new "--local_tmp_root=<path>" flag allows specifying the temp
>    directory for locally executed actions.
>    ...
>  - The new "--local_tmp_root=<path>" flag allows specifying the temp
>    directory for locally executed actions.
> ...
>   - None
>    TESTED=presubmit, next cl
> ...
> - None (select branches are mutually exclusive, so this is a no-op)

**Comment by meteorcloudy** [comment]
@laszlocsomor , thanks! I'll make sure they don't appear in the next RC.

**Comment by ahumesky** [comment]
I've sent out a change removing the usage of the manifest_merger attribute from tensorflow (It's basically an internal-only attribute and it was sort of an accident that it was released as part of the tensorflow demo)

**Comment by steeve** [comment]
Can we cherry-pick https://github.com/bazelbuild/bazel/commit/cb16c5089953127690c8971d32dc3d4cf01b7620 please pretty please ? Thank you!

**Comment by meteorcloudy** [comment]
@steeve  cb16c50 is included in this release, no need to cherry-pick.

**Comment by steeve** [comment]
That's great thank you!

**Comment by brandjon** [comment]
FYI: Be advised that #5010 may lead to Skylark breakages if users are passing certain args by keyword. Skylark team expects the effect to be pretty minor, but if we're wrong we can make a patch. We're hoping to not have to do that since the behavior being broken is questionable anyway.

**Comment by laszlocsomor** [comment]
https://github.com/bazelbuild/bazel/issues/5038 is a blocker.

**Comment by laszlocsomor** [comment]
Please cherry-pick https://github.com/bazelbuild/bazel/commit/f083e7623cd03e20ed216117c5ea8c8b4ec61948 to fix #5038.

**Comment by meteorcloudy** [comment]
New cherry-pick fa36d2f48965b127e8fd397348d16e991135bfb6 for fixing #4928

**Comment by meteorcloudy** [comment]
0.13.0rc2 is created with `scripts/release/release.sh create 0.13.0 fdee70e f083e76 fa36d2f `, but haven't been pushed yet.
Building at https://buildkite.com/bazel/release/builds/30

**Comment by petemounce** [comment]
0.13.0-rc2 is up on chocolatey.

**Comment by jin** [comment]
Is it possible to cherrypick https://github.com/bazelbuild/bazel/commit/4abd2babcc50900afd0271bf30dc64055f34e100 to fix https://github.com/bazelbuild/bazel/issues/5077?

**Comment by meteorcloudy** [comment]
Sorry @jin, #5077 isn't a regression in 0.13.0, so I think we'll have to wait until 0.14.0. 
I'll try to release 0.13.0 ASAP!

**Comment by laszlocsomor** [comment]
https://github.com/bazelbuild/bazel/issues/5079 is a blocker

**Comment by meteorcloudy** [comment]
Considering #4751 is also a bug already existing in 0.12.0, I'm removing it as a release blocker.
So, there is currently no unfixed release blocker. I'll wait for one more day in case there's any objection, if none, I'll release 0.13.0 on Wednesday.

**Comment by laszlocsomor** [comment]
> Considering #4751 is also a bug already existing in 0.12.0

What about #5079? It's not a regression since 0.12.0, but it makes Bazel unusable for tests in the `//` package.

**Comment by meteorcloudy** [comment]
OK, then I'll cherry-pick the fixes for both #5079 and #5077. But still leaving #4751 not being release blocker, because we are not making progress on fixing it and the issue only happens when using http remote cache on macOS, which is not used often by our users.

**Comment by laszlocsomor** [comment]
Please cherry-pick 2c957575ff24c183d48ade4345a79ffa5bec3724 to fix #5079.

**Comment by meteorcloudy** [comment]
@laszlocsomor Thank you!

**Comment by jin** [comment]
@meteorcloudy thank you!

**Comment by meteorcloudy** [comment]
0.13.0rc3 has been created with 
`scripts/release/release.sh create 0.13.0 fdee70e f083e76 fa36d2f 4abd2ba 2c95757`
Available at: https://releases.bazel.build/0.13.0/rc3/index.html
Thanks to @philwo !

**Comment by meteorcloudy** [comment]
A new release blocker is discovered: #5066

**Comment by meteorcloudy** [comment]
0.13.0rc4 has been created with 
`scripts/release/release.sh create 0.13.0 fdee70e f083e76 fa36d2f 4abd2ba 2c95757 f0cd2d2 `
Available at: https://releases.bazel.build/0.13.0/rc4/index.html

**Comment by meteorcloudy** [comment]
Unfortunately, rc4 is bad due to a merge conflict error, please don't use it. I'm fixing it.
Sorry for the trouble

**Comment by meteorcloudy** [comment]
0.13.0rc5 has been created with
scripts/release/release.sh create 0.13.0 fdee70e f083e76 fa36d2f 4abd2ba 2c95757
Available at: https://releases.bazel.build/0.13.0/rc5/index.html

rc5 is for undoing rc4, it's exactly the same as rc3

**Comment by meteorcloudy** [comment]
We have the 0.13.0 release:
https://github.com/bazelbuild/bazel/releases/tag/0.13.0

**Comment by petemounce** [comment]
Chocolatey package is published.

**Comment by werkt** [comment]
Remote Ex for 0.13.0 is producing directories with unsorted file/directory lists. This was a regression introduced in 0.12.0 (verified with deb testing of 0.11.1, 0.12.0, and 0.13.0). Issue was filed as #5109 with supplied PR #5110. Recommend inclusion into a patch release, as this will be broken against any validating Remote Ex Execution Service (including [buildfarm](https://github.com/bazelbuild/bazel-buildfarm/blob/24a5d7e295d20ffeb2306c2f5ddfdc08cfd56c46/src/main/java/build/buildfarm/instance/AbstractServerInstance.java#L235,L295))
