### ISSUE TITLE
mobile-install v1 umbrella bug

### ISSUE THREAD

**Issue by jin** [bazelbuild/bazel#6814]
This is an umbrella bug to track issues related to mobile-install v1.

- [x] Incompatibility with aapt2 https://github.com/bazelbuild/bazel/issues/5799, will unblock https://github.com/bazelbuild/bazel/issues/4103
- [ ] `adb push` permissions issue https://github.com/bazelbuild/examples/issues/77
- [x] mobile-install on Android 9: `java.lang.NoSuchMethodException: android.content.res.AssetManager.ensureStringBlocks []` https://groups.google.com/forum/#!searchin/bazel-discuss/mobile-install%7Csort:date/bazel-discuss/A4B8-GmBHxI/yoVNKuQ1BAAJ 

Note that mobile-install v1 will be deprecated as soon as mobile-install v2 (written in Starlark) is open sourced, so we'll need to revisit these issues and ensure that mi-v2 fixes them.

**Comment by jin** [comment]
cc @jgavris

**Comment by jin** [comment]
Update: I'm drafting a plan to open source mi-v2, which involves open sourcing a lot of its tool dependencies.

**Comment by JiamingFB** [comment]
Hi Jin, I'm facing the same bug on Android 9.

java.lang.RuntimeException: Unable to create application com.google.devtools.build.android.incrementaldeployment.StubApplication: java.lang.IllegalStateException: java.lang.NoSuchMethodException: ensureStringBlocks []

In addition, I can't disable incremental build with either "--noincremental" or "--incremental=false" flag. bazel mobile-install always use incremental deployment instead of full build.

**Comment by jin** [comment]
@JiamingFB I have a fix pending for that.

**Comment by jin** [comment]
I also have a fix pending for the incompatibility with aapt2.

**Comment by jin** [comment]
@JiamingFB fix it out, you'll need to build Bazel at HEAD to use it, or use Bazel 0.22 when it's released.

**Comment by jgavris** [comment]
Thanks @jin! So this will definitely land in 0.22?

**Comment by jin** [comment]
Yes!
